Repository libp2p/rust-libp2p, pull requests merged in 2018-08, with the labels that each got.

#382 Remove travis.yml
  .travis.yml
Labels: pr-good-waiting-for-ci

#383 Update the P2P multiaddr component to 421
  floodsub/src/lib.rs
  identify/src/peer_id_transport.rs
  libp2p/examples/kademlia.rs
  multiaddr/src/protocol.rs
  multiaddr/tests/lib.rs
  relay/src/utility.rs
Labels: pr-good-waiting-for-ci, pr-queued-to-merge

#373 Fix peers() always returning empty results
  peerstore/src/json_peerstore.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#370 Rewrite multiplex tests to use the memory transport
  core/tests/multiplex.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#357 Strongly type AddrComponent::{P2P, IPFS} with Cids
  floodsub/src/lib.rs
  identify/src/peer_id_transport.rs
  libp2p/examples/kademlia.rs
  multiaddr/src/lib.rs
  multiaddr/src/protocol.rs
  relay/src/utility.rs
Labels: in progress, pr-needs-review

#381 Make ping unidirectional
  core/src/lib.rs
  libp2p/examples/ping-client.rs
  ping/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#384 Fix decode data UnexpectedEof bug
  varint-rs/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci

#395 Add some From impls for AddrComponent
  multiaddr/src/protocol.rs
Labels: in progress

#366 Rework swarm and allow interrupting a dial
  core/Cargo.toml
  core/src/lib.rs
  core/src/swarm.rs
  core/src/transport/interruptible.rs
  core/src/transport/mod.rs
  core/src/unique.rs
  libp2p/examples/kademlia.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#308 Add a UNIX transport
  Cargo.toml
  README.md
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  uds/Cargo.toml
  uds/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#402 Use tk_listen to absorb errors on the TcpListener
  tcp-transport/Cargo.toml
  tcp-transport/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#404 Tcp refinements
  tcp-transport/src/lib.rs
Labels: in progress

#403 Rework the multihash crate
  cid/src/error.rs
  cid/src/lib.rs
  cid/src/to_cid.rs
  cid/tests/lib.rs
  core/src/peer_id.rs
  kad/src/kbucket.rs
  libp2p/examples/kademlia.rs
  multihash/src/errors.rs
  multihash/src/hashes.rs
  multihash/src/lib.rs
  multihash/tests/lib.rs
Labels: P-important, P0 - Critical, in progress

#398 Add CircleCI build for win32
  .circleci/config.yml
Labels: in progress

#329 Use unsigned-varint crate.
  Cargo.toml
  floodsub/Cargo.toml
  floodsub/src/lib.rs
  identify/Cargo.toml
  identify/src/lib.rs
  identify/src/protocol.rs
  kad/Cargo.toml
  kad/src/lib.rs
  kad/src/protocol.rs
  mplex/Cargo.toml
  mplex/src/codec.rs
  mplex/src/lib.rs
  multistream-select/Cargo.toml
  multistream-select/src/lib.rs
  multistream-select/src/protocol/dialer.rs
  multistream-select/src/protocol/error.rs
  multistream-select/src/protocol/listener.rs
  relay/Cargo.toml
  relay/src/lib.rs
  relay/src/utility.rs
  varint-rs/.gitignore
  varint-rs/Cargo.toml
  varint-rs/src/lib.rs
Labels: in progress

#394 Add upgrade::loop_upg
  core/src/upgrade/apply.rs
  core/src/upgrade/loop_upg.rs
  core/src/upgrade/mod.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#407 Use a Multihash in AddrComponent::P2P, drop cid
  Cargo.toml
  cid/.gitignore
  cid/.travis.yml
  cid/Cargo.toml
  cid/README.md
  cid/src/codec.rs
  cid/src/error.rs
  cid/src/lib.rs
  cid/src/to_cid.rs
  cid/src/version.rs
  cid/tests/lib.rs
  core/src/peer_id.rs
  floodsub/src/lib.rs
  identify/src/peer_id_transport.rs
  libp2p/examples/kademlia.rs
  multiaddr/Cargo.toml
  multiaddr/src/errors.rs
  multiaddr/src/lib.rs
  multiaddr/src/protocol.rs
  relay/src/utility.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#386 remove rustc-serialize (#359)
  secio/Cargo.toml
  secio/src/algo_support.rs
  secio/src/codec/decode.rs
  secio/src/codec/encode.rs
  secio/src/codec/mod.rs
  secio/src/error.rs
  secio/src/handshake.rs
  secio/src/lib.rs
  secio/src/stream_cipher.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#360 Fixes to the mplex implementation
  mplex/Cargo.toml
  mplex/src/codec.rs
  mplex/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-needs-work, pr-queued-to-merge

#415 Complements to #389
  secio/src/codec/decode.rs
  secio/src/codec/encode.rs
  secio/src/codec/mod.rs
  secio/src/stream_cipher.rs
Labels: in progress

#392 Add Transport::map_err_dial
  core/src/transport/map_err_dial.rs
  core/src/transport/mod.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#411 Allow configuring mplex
  mplex/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#327 Simplify the implementation of peer_info
  multiaddr/Cargo.toml
  multiaddr/src/lib.rs
  multiaddr/tests/lib.rs
  peerstore/Cargo.toml
  peerstore/src/peer_info.rs
Labels: in progress, pr-needs-review

#391 Better documentation
  README.md
  core/README.md
  core/src/lib.rs
  core/src/transport/mod.rs
  datastore/README.md
  datastore/src/lib.rs
  dns/README.md
  dns/src/lib.rs
  libp2p/examples/README.md
  libp2p/src/lib.rs
  mplex/README.md
  multiaddr/README.md
  multihash/README.md
  multistream-select/README.md
  multistream-select/src/lib.rs
  peerstore/README.md
  ping/README.md
  ping/src/lib.rs
  relay/README.md
  rw-stream-sink/README.md
  rw-stream-sink/src/lib.rs
  secio/README.md
  tcp-transport/README.md
  tcp-transport/src/lib.rs
  websocket/README.md
  websocket/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#430 Fix rust-libp2p issue #429 (floodsub fails to decode PeerId)
  protocols/floodsub/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#438 Correctly encode and decode multistream-select ls.
  misc/multistream-select/src/protocol/dialer.rs
  misc/multistream-select/src/protocol/listener.rs
Labels: in progress

#437 Rework the StreamMuxer trait
  core/src/connection_reuse.rs
  core/src/either.rs
  core/src/muxing.rs
  core/tests/multiplex.rs
  muxers/mplex/src/lib.rs
  muxers/mplex/tests/two_peers.rs
  muxers/yamux/Cargo.toml
  muxers/yamux/src/lib.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge
