Repository libp2p/rust-libp2p, pull requests merged in 2018-11, with the labels that each got.

#573 Add ProtocolsHandler trait
  core/Cargo.toml
  core/src/lib.rs
  core/src/nodes/handled_node.rs
  core/src/nodes/mod.rs
  core/src/nodes/protocols_handler.rs
Labels: pr-queued-to-merge

#546 Tests for HandledNode
  core/src/nodes/handled_node.rs
  core/src/nodes/node.rs
  core/src/tests/dummy_handler.rs
  core/src/tests/dummy_muxer.rs
  core/src/tests/mod.rs
Labels: pr-queued-to-merge

#583 Add a peer id generator
  Cargo.toml
  misc/peer-id-generator/Cargo.toml
  misc/peer-id-generator/src/main.rs
Labels: pr-queued-to-merge

#610 Use vecdeque for fair polling
  core/src/nodes/listeners.rs
Labels: pr-needs-review

#616 Use upstream rust-secp256k1
  protocols/secio/Cargo.toml
  protocols/secio/src/handshake.rs
  protocols/secio/src/lib.rs
Labels: pr-queued-to-merge

#625 Use expect rather than unwrap
  protocols/kad/src/kbucket.rs
Labels: pr-queued-to-merge

#622 Set the maximum size of Mplex messages to 1Mb
  muxers/mplex/src/codec.rs
Labels: pr-needs-review

#629 Tweaks, spelling and grammar
  core/src/nodes/protocols_handler.rs
Labels: pr-queued-to-merge

#584 Tests for HandledNodesTasks
  core/src/nodes/handled_node.rs
  core/src/nodes/handled_node_tasks.rs
  core/src/tests/dummy_handler.rs
  core/src/tests/dummy_muxer.rs
  core/src/tests/dummy_transport.rs
Labels: pr-needs-review

#635 Fix the concerns of #603
  protocols/floodsub/src/handler.rs
  protocols/floodsub/src/layer.rs
  protocols/floodsub/src/protocol.rs
Labels: pr-queued-to-merge

#638 Update connected peers' topics on NodeEvent
  protocols/floodsub/src/layer.rs
Labels: pr-queued-to-merge

#634 Use a random sequence number in floodsub
  protocols/floodsub/Cargo.toml
  protocols/floodsub/src/layer.rs
  protocols/floodsub/src/lib.rs
Labels: pr-queued-to-merge

#631 Send Close when shutting down gracefully, as per spec
  muxers/mplex/src/lib.rs
Labels: pr-needs-review

#588 Tests for CollectionStream
  core/src/nodes/collection.rs
  core/src/nodes/handled_node.rs
Labels: pr-needs-review

#654 Fix mapping of upgrade.
  core/src/protocols_handler.rs
  core/src/upgrade/map.rs
  core/src/upgrade/mod.rs
Labels: in progress

#653 Add `upgrade::apply` for convenience.
  core/src/upgrade/apply.rs
  core/src/upgrade/mod.rs
Labels: in progress

#656 Fix mapping of upgrade errors.
  core/src/protocols_handler.rs
  core/src/upgrade/map.rs
  core/src/upgrade/mod.rs
Labels: in progress

#641 Floodsub chat example
  Cargo.toml
  core/src/lib.rs
  examples/chat.rs
  src/lib.rs
Labels: in progress, pr-needs-review

#661 Add PeerId::random()
  core/src/nodes/collection.rs
  core/src/nodes/handled_node_tasks.rs
  core/src/peer_id.rs
  misc/multihash/Cargo.toml
  misc/multihash/src/lib.rs
  protocols/kad/src/kad_server.rs
  protocols/kad/src/protocol.rs
  stores/peerstore/src/json_peerstore.rs
  stores/peerstore/src/lib.rs
  stores/peerstore/src/peerstore_tests.rs
Labels: in progress

#666 A few typos
  core/src/lib.rs
  protocols/ping/src/lib.rs
  protocols/ping/src/protocol.rs
Labels: pr-needs-review

#667 secio: Defer nonce verification.
  protocols/secio/src/codec/decode.rs
  protocols/secio/src/codec/mod.rs
  protocols/secio/src/handshake.rs
  protocols/secio/src/lib.rs
Labels: in progress

#665 Export plaintext from the root
  Cargo.toml
  src/lib.rs
Labels: in progress, pr-needs-review

#669 Remove _priv from IdentifyInfo
  protocols/identify/src/protocol.rs
Labels: in progress

#663 Remove the NamesIter: Clone requirement
  core/src/nodes/swarm.rs
  core/src/protocols_handler.rs
  core/src/transport/upgrade.rs
  core/src/upgrade/apply.rs
  misc/multistream-select/src/lib.rs
  misc/multistream-select/src/listener_select.rs
  misc/multistream-select/src/tests.rs
Labels: in progress

#677 rw-stream-sink: Skip over empty stream items.
  misc/rw-stream-sink/src/lib.rs
Labels: in progress

#678 examples: Use logger in chat example.
  examples/chat.rs
Labels: in progress

#676 docs: add libp2p badges
  README.md
Labels: pr-queued-to-merge

#590 Add libp2p-mdns
  Cargo.toml
  core/src/peer_id.rs
  examples/mdns-passive-discovery.rs
  misc/mdns/Cargo.toml
  misc/mdns/src/dns.rs
  misc/mdns/src/lib.rs
  src/lib.rs
Labels: in progress, pr-queued-to-merge

#602 Tests for RawSwarm
  core/src/nodes/listeners.rs
  core/src/nodes/raw_swarm.rs
  core/src/tests/dummy_muxer.rs
  core/src/tests/dummy_transport.rs
  core/src/transport/mod.rs
Labels: in progress, pr-needs-review

#683 rw-stream-sink: Add regression test.
  misc/rw-stream-sink/src/lib.rs
Labels: in progress

#673 Remove several unused transports.
  core/src/transport/denied.rs
  core/src/transport/interruptible.rs
  core/src/transport/mod.rs
  core/src/upgrade/denied.rs
  transports/relay/src/transport.rs
  transports/websocket/src/browser.rs
Labels: in progress

#680 Split the `protocols_handler.rs` module into multiple submodules
  core/src/protocols_handler.rs
  core/src/protocols_handler/dummy.rs
  core/src/protocols_handler/map_in.rs
  core/src/protocols_handler/map_out.rs
  core/src/protocols_handler/mod.rs
  core/src/protocols_handler/node_handler.rs
  core/src/protocols_handler/select.rs
Labels: in progress, pr-queued-to-merge

#671 Avoid boxing in transport combinators.
  core/src/transport/and_then.rs
  core/src/transport/map.rs
  core/src/transport/map_err_dial.rs
  core/src/transport/mod.rs
Labels: in progress

#686 Update some dependencies
  Cargo.toml
  core/Cargo.toml
  misc/mdns/Cargo.toml
  misc/multiaddr/Cargo.toml
  misc/multihash/Cargo.toml
  misc/peer-id-generator/Cargo.toml
  muxers/mplex/Cargo.toml
  muxers/yamux/Cargo.toml
  protocols/floodsub/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/kad/Cargo.toml
  protocols/ping/Cargo.toml
  protocols/secio/Cargo.toml
  protocols/secio/src/lib.rs
  transports/dns/Cargo.toml
  transports/relay/Cargo.toml
Labels: in progress

#689 Fix the custom derive
  core/src/protocols_handler/select.rs
  misc/core-derive/src/lib.rs
  misc/core-derive/tests/test.rs
Labels: P-important, in progress

#690 Fix Transport::and_then
  core/src/transport/and_then.rs
Labels: in progress

#688 Fix a typo and grammar and add a clarification.
  core/src/nodes/handled_node_tasks.rs
Labels: in progress

#693 Add a warning about being conformant
  README.md
Labels: in progress

#700 Add 'of'
  core/src/nodes/collection.rs
Labels: in progress

#580 Add a KademliaHandler
  core/src/peer_id.rs
  core/src/swarm.rs
  core/src/topology/mod.rs
  examples/ipfs-kad.rs
  misc/core-derive/src/lib.rs
  misc/core-derive/tests/test.rs
  protocols/floodsub/src/layer.rs
  protocols/identify/src/listen_layer.rs
  protocols/identify/src/periodic_id_layer.rs
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour.rs
  protocols/kad/src/handler.rs
  protocols/kad/src/high_level.rs
  protocols/kad/src/kad_server.rs
  protocols/kad/src/kbucket.rs
  protocols/kad/src/lib.rs
  protocols/kad/src/protocol.rs
  protocols/kad/src/query.rs
  protocols/kad/src/topology.rs
  protocols/ping/src/dial_layer.rs
  protocols/ping/src/listen_layer.rs
Labels: in progress

#701 Chore/grammar
  core/src/nodes/collection.rs
  core/src/nodes/handled_node_tasks.rs
  core/src/nodes/raw_swarm.rs
  examples/chat.rs
  protocols/floodsub/src/layer.rs
  protocols/identify/src/id_transport.rs
  protocols/identify/src/listen_layer.rs
Labels: in progress

#707 Fix core-derive
  misc/core-derive/src/lib.rs
  misc/core-derive/tests/test.rs
Labels: in progress

#684 Revamp the documentation of the root of core
  core/src/lib.rs
Labels: in progress

#709 Use UpgradeError::into_io_error
  core/src/transport/upgrade.rs
Labels: in progress

#705 Add &message.source in println! as per …
  examples/chat.rs
Labels: in progress

#714 multiaddr: change UDP constant from 17 to 273.
  misc/multiaddr/src/protocol.rs
  misc/multiaddr/tests/lib.rs
Labels: in progress
