Repository libp2p/rust-libp2p, pull requests merged in 2018-09, with the labels that each got.

#439 multistream-select: Include `\n` in length.
  misc/multistream-select/src/protocol/listener.rs
  misc/multistream-select/src/tests.rs
Labels: in progress

#445 Simplify the mplex codec implementation
  muxers/mplex/src/codec.rs
Labels: in progress

#446 Merge the changes from polkadot-2 into master
  core/src/connection_reuse.rs
  core/src/transport/mod.rs
  core/src/transport/upgrade.rs
  core/tests/multiplex.rs
  examples/echo-dialer.rs
  examples/echo-server.rs
  examples/floodsub.rs
  examples/kademlia.rs
  examples/ping-client.rs
  examples/relay.rs
Labels: in progress, pr-good-waiting-for-ci, pr-queued-to-merge

#447 Update unsigned-varint crate to v0.2.0
  misc/multistream-select/Cargo.toml
  muxers/mplex/Cargo.toml
  protocols/floodsub/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/kad/Cargo.toml
  transports/relay/Cargo.toml
Labels: in progress

#449 Cap the allocated buffer capacity in mplex
  muxers/mplex/src/lib.rs
Labels: in progress

#448 Downgrade ring to 0.12
  protocols/secio/Cargo.toml
Labels: in progress, pr-queued-to-merge

#442 The SwarmFuture is now a Stream
  core/src/lib.rs
  core/src/swarm.rs
  core/src/transport/memory.rs
  core/src/unique.rs
  core/tests/lots_of_connec.rs
  examples/echo-dialer.rs
  examples/echo-server.rs
  examples/floodsub.rs
  examples/kademlia.rs
  examples/ping-client.rs
  examples/relay.rs
Labels: in progress

#418 Make the Futures in map_err Send-friendly
  core/src/transport/map_err.rs
Labels: in progress

#436 Issue 434
  core/src/upgrade/traits.rs
  muxers/mplex/src/codec.rs
  muxers/mplex/src/lib.rs
Labels: in progress, on-ice

#453 Add some comments about the notification behaviour of muxers
  core/src/muxing.rs
Labels: pr-queued-to-merge

#454 Populate TcpConfig with more config
  transports/tcp/src/lib.rs
Labels: in progress

#474 Secp256k1 key generation
  protocols/secio/src/lib.rs
Labels: pr-needs-review
