Repository libp2p/rust-libp2p, pull requests merged in 2019-02, with the labels that each got.

#907 Fix the dialing priority system
  core/Cargo.toml
  core/src/nodes/raw_swarm.rs
  core/src/nodes/raw_swarm/tests.rs
  core/tests/raw_swarm_simult.rs
Labels: in progress

#915 Add Swarm::add_external_address
  core/src/swarm.rs
Labels: in progress

#914 Add NetworkBehaviour::inject_replaced
  core/src/swarm.rs
  misc/core-derive/src/lib.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/query.rs
Labels: changelog, in progress

#916 Bump libp2p, libp2p-core, libp2p-core-derive and libp2p-kad
  CHANGELOG.md
  Cargo.toml
  core/Cargo.toml
  misc/core-derive/Cargo.toml
  protocols/kad/Cargo.toml
Labels: in progress

#920 Limit Kademlia messages to 4kiB
  protocols/kad/Cargo.toml
  protocols/kad/src/protocol.rs
Labels: in progress

#922 Fix generics in out_event type in derive
  misc/core-derive/Cargo.toml
  misc/core-derive/src/lib.rs
  misc/core-derive/tests/test.rs
Labels: in progress

#926 Report external addresses in identify
  protocols/identify/Cargo.toml
  protocols/identify/src/identify.rs
Labels: in progress

#927 Fix duplicate external addresses inserted
  core/Cargo.toml
  core/src/swarm.rs
Labels: in progress

#931 Update Dependencies
  misc/multiaddr/Cargo.toml
  misc/multiaddr/src/errors.rs
  protocols/secio/Cargo.toml
  protocols/secio/src/codec/mod.rs
  protocols/secio/src/handshake.rs
  protocols/secio/src/lib.rs
  transports/websocket/Cargo.toml
Labels: pr-needs-review

#930 Send external addresses first in identify
  protocols/identify/src/identify.rs
Labels: in progress

#932 Update the WASM docker image
  .circleci/config.yml
Labels: in progress

#910 Fix infinite loop in read_one
  core/src/upgrade/transfer.rs
Labels: in progress

#934 Fix compiling for WASM with websockets disabled
  core/src/transport/dummy.rs
  core/src/transport/mod.rs
  src/lib.rs
Labels: in progress

#928 Add a proper list of addresses type for Kademlia
  protocols/kad/src/addresses.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/lib.rs
Labels: changelog, in progress

#937 Improvements to the helpers in upgrade::transfer
  core/src/upgrade/mod.rs
  core/src/upgrade/transfer.rs
  protocols/floodsub/src/protocol.rs
Labels: changelog, in progress

#918 Add Ord implementation for KeepAlive
  core/src/protocols_handler/mod.rs
  core/src/protocols_handler/select.rs
Labels: in progress

#941 Add IdentifyEvent::SendBack event
  protocols/identify/src/identify.rs
Labels: changelog, in progress

#917 Improve nodes state
  core/src/nodes/collection.rs
  core/src/nodes/collection/tests.rs
  core/src/nodes/handled_node_tasks.rs
  core/src/nodes/handled_node_tasks/tests.rs
  protocols/identify/src/periodic_id_handler.rs
Labels: changelog, in progress

#911 Add a BandwidthLogging transport wrapper
  Cargo.toml
  src/bandwidth.rs
  src/lib.rs
  src/transport_ext.rs
Labels: changelog, in progress

#943 Accept empty substreams in read_one
  core/src/upgrade/transfer.rs
Labels: in progress

#946 Minor optimisation in Fuse::poll
  core/src/protocols_handler/fuse.rs
Labels: in progress

#944 Decode multiaddresses from visit_seq
  misc/multiaddr/src/lib.rs
Labels: in progress

#948 Fix the multiaddr reexport
  misc/multiaddr/src/lib.rs
  src/lib.rs
Labels: changelog, in progress

#949 Revert erroneous change in identification delay, and add test for it
  protocols/identify/Cargo.toml
  protocols/identify/src/identify.rs
  protocols/identify/src/periodic_id_handler.rs
Labels: in progress

#947 Add a user data to `CollectionStream`
  core/src/nodes/collection.rs
  core/src/nodes/collection/tests.rs
  core/src/nodes/handled_node_tasks.rs
  core/src/nodes/raw_swarm.rs
Labels: changelog, in progress

#951 Rewrite the MemoryTransport to be similar to the TcpConfig
  core/Cargo.toml
  core/src/nodes/listeners.rs
  core/src/nodes/raw_swarm/tests.rs
  core/src/transport/memory.rs
  core/src/transport/mod.rs
  misc/multiaddr/src/protocol.rs
  misc/multiaddr/tests/lib.rs
Labels: changelog, in progress

#952 Fix the identify test multiplexer
  protocols/identify/src/identify.rs
Labels: in progress

#954 Use different ports in the memory transport tests
  core/src/transport/memory.rs
Labels: in progress

#956 Make TcpConfig::nat_traversal work with IPv6
  transports/tcp/src/lib.rs
Labels: changelog, in progress

#961 Fix an infinite loop in ProtocolsHandlerSelect
  core/src/protocols_handler/fuse.rs
  core/src/protocols_handler/select.rs
Labels: in progress

#962 Add dialing error tests for the raw swarm
  core/tests/raw_swarm_dial_error.rs
Labels: in progress

#957 Fix simultaneous dialing test
  core/src/either.rs
  core/src/muxing.rs
  core/src/nodes/collection.rs
  core/src/nodes/handled_node.rs
  core/src/nodes/handled_node_tasks.rs
  core/src/nodes/handled_node_tasks/tests.rs
  core/src/nodes/node.rs
  core/src/nodes/raw_swarm.rs
  core/src/tests/dummy_muxer.rs
  core/tests/raw_swarm_simult.rs
  muxers/mplex/src/lib.rs
  muxers/yamux/src/lib.rs
Labels: changelog, in progress

#964 Bump to v0.4
  CHANGELOG.md
  Cargo.toml
  core/Cargo.toml
  misc/core-derive/Cargo.toml
  misc/mdns/Cargo.toml
  misc/multiaddr/Cargo.toml
  misc/peer-id-generator/Cargo.toml
  muxers/mplex/Cargo.toml
  muxers/yamux/Cargo.toml
  protocols/floodsub/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/kad/Cargo.toml
  protocols/noise/Cargo.toml
  protocols/observed/Cargo.toml
  protocols/ping/Cargo.toml
  protocols/plaintext/Cargo.toml
  protocols/secio/Cargo.toml
  transports/dns/Cargo.toml
  transports/ratelimit/Cargo.toml
  transports/tcp/Cargo.toml
  transports/uds/Cargo.toml
  transports/websocket/Cargo.toml
Labels: in progress

#965 Forgot line in changelog
  CHANGELOG.md
Labels: in progress

#966 Fix version of noise
  CHANGELOG.md
  Cargo.toml
  protocols/noise/Cargo.toml
Labels: in progress

#969 Switch the WASM image to something else
  .circleci/config.yml
Labels: in progress

#977 Disconnect only after the identify answer
  protocols/identify/src/periodic_id_handler.rs
Labels: in progress

#979 Ping wasn't working anymore
  protocols/ping/src/handler.rs
  protocols/ping/src/lib.rs
Labels: changelog, in progress

#981 Bump to v0.4.2
  CHANGELOG.md
  Cargo.toml
  protocols/identify/Cargo.toml
  protocols/ping/Cargo.toml
Labels: in progress

#975 Fall back if no tokio executor available
  core/src/nodes/handled_node_tasks.rs
Labels: in progress
