Repository libp2p/rust-libp2p, pull requests merged in 2019-04, with the labels that each got.

#1040 Add missing zeroize() call for secp256k1::SecretKey::from_bytes.
  core/src/identity/secp256k1.rs
Labels: in progress

#1035 Split the Swarm from the NetworkBehaviour
  core/src/swarm.rs
  core/src/swarm/behaviour.rs
  core/src/swarm/swarm.rs
Labels: in progress

#1043 Remove `ProtocolsHandlerUpgrErr::MuxerDeniedSubstream`.
  core/src/protocols_handler/mod.rs
  core/src/protocols_handler/select.rs
Labels: in progress

#1039 Allow oneshot handler's inactivity_timeout to be configurable
  core/src/protocols_handler/one_shot.rs
Labels: changelog, in progress

#1037 Add some more getters to RawSwarm
  core/src/nodes/raw_swarm.rs
Labels: in progress

#1045 Generalize TPeerId into TConnInfo
  core/src/nodes/collection.rs
  core/src/nodes/handled_node_tasks.rs
  core/src/nodes/mod.rs
  core/src/nodes/raw_swarm.rs
  core/src/nodes/raw_swarm/tests.rs
  core/src/swarm/swarm.rs
  core/tests/raw_swarm_simult.rs
Labels: changelog, in progress

#1046 Add ExpandedSwarm
  core/src/swarm.rs
  core/src/swarm/swarm.rs
Labels: in progress

#1041 Change `Multiaddr` representation to `Bytes`.
  misc/multiaddr/Cargo.toml
  misc/multiaddr/src/lib.rs
  misc/multiaddr/tests/lib.rs
  protocols/identify/src/protocol.rs
  protocols/kad/src/protocol.rs
  protocols/observed/src/lib.rs
Labels: in progress

#1032 Have `Transport::Listener`s produce `ListenerEvent`s.
  core/src/either.rs
  core/src/lib.rs
  core/src/nodes/listeners.rs
  core/src/nodes/raw_swarm.rs
  core/src/nodes/raw_swarm/tests.rs
  core/src/swarm.rs
  core/src/swarm/swarm.rs
  core/src/tests/dummy_handler.rs
  core/src/tests/dummy_transport.rs
  core/src/transport/and_then.rs
  core/src/transport/boxed.rs
  core/src/transport/choice.rs
  core/src/transport/dummy.rs
  core/src/transport/map.rs
  core/src/transport/map_err.rs
  core/src/transport/memory.rs
  core/src/transport/mod.rs
  core/src/transport/timeout.rs
  core/src/transport/upgrade.rs
  core/tests/raw_swarm_dial_error.rs
  core/tests/raw_swarm_simult.rs
  muxers/mplex/tests/two_peers.rs
  protocols/identify/Cargo.toml
  protocols/identify/src/id_transport.rs
  protocols/identify/src/identify.rs
  protocols/identify/src/protocol.rs
  protocols/kad/src/behaviour/test.rs
  protocols/noise/tests/smoke.rs
  src/bandwidth.rs
  src/lib.rs
  transports/dns/src/lib.rs
  transports/ratelimit/src/lib.rs
  transports/tcp/src/lib.rs
  transports/uds/src/lib.rs
  transports/websocket/src/browser.rs
  transports/websocket/src/desktop.rs
Labels: in progress

#1050 Patch reading/writing frame lengths in libp2p-noise.
  protocols/noise/src/io.rs
Labels: in progress

#980 Rewrite the WebCrypto ECDH using wasm-bindgen
  protocols/secio/Cargo.toml
  protocols/secio/src/exchange/impl_webcrypto.rs
  protocols/secio/src/lib.rs
Labels: changelog, in progress

#1044 Expand wildcard IP addresses in TCP transport.
  core/src/transport/mod.rs
  muxers/mplex/tests/two_peers.rs
  protocols/identify/src/protocol.rs
  transports/tcp/Cargo.toml
  transports/tcp/src/lib.rs
Labels: changelog, in progress

#1062 Fix the WASM build
  transports/websocket/Cargo.toml
Labels: in progress

#1059 Update README.md
  README.md
Labels: in progress

#1061 Add NetworkBehaviour methods for listened addresses
  core/src/swarm/behaviour.rs
  core/src/swarm/swarm.rs
  core/src/swarm/toggle.rs
  misc/core-derive/src/lib.rs
Labels: changelog, in progress

#1049 libp2p-ping improvements.
  core/src/protocols_handler/dummy.rs
  core/src/protocols_handler/map_in.rs
  core/src/protocols_handler/map_out.rs
  core/src/protocols_handler/mod.rs
  core/src/protocols_handler/node_handler.rs
  core/src/protocols_handler/one_shot.rs
  core/src/protocols_handler/select.rs
  core/src/swarm/behaviour.rs
  core/src/swarm/swarm.rs
  core/src/swarm/toggle.rs
  core/tests/raw_swarm_dial_error.rs
  core/tests/raw_swarm_simult.rs
  examples/ping.rs
  protocols/identify/src/listen_handler.rs
  protocols/identify/src/periodic_id_handler.rs
  protocols/kad/src/handler.rs
  protocols/ping/Cargo.toml
  protocols/ping/src/handler.rs
  protocols/ping/src/lib.rs
  protocols/ping/src/protocol.rs
  protocols/ping/tests/ping.rs
  src/lib.rs
Labels: changelog, in progress

#1063 Add NetworkBehaviour::inject_new_external_addr
  core/src/swarm/behaviour.rs
  core/src/swarm/swarm.rs
  core/src/swarm/toggle.rs
  misc/core-derive/src/lib.rs
Labels: changelog, in progress

#1064 Update examples to print a listen address.
  examples/chat.rs
  examples/ping.rs
Labels: in progress

#1060 Add some TryFrom implementations
  core/src/peer_id.rs
  misc/multihash/src/lib.rs
Labels: in progress

#1052 Remove `Transport::nat_traversal` and refactor `multiaddr`.
  core/src/lib.rs
  core/src/nodes/raw_swarm.rs
  core/src/nodes/raw_swarm/tests.rs
  core/src/swarm/swarm.rs
  core/src/tests/dummy_transport.rs
  core/src/translation.rs
  core/src/transport/and_then.rs
  core/src/transport/boxed.rs
  core/src/transport/choice.rs
  core/src/transport/dummy.rs
  core/src/transport/map.rs
  core/src/transport/map_err.rs
  core/src/transport/memory.rs
  core/src/transport/mod.rs
  core/src/transport/timeout.rs
  core/src/transport/upgrade.rs
  misc/mdns/src/behaviour.rs
  misc/multiaddr/src/lib.rs
  misc/multiaddr/src/util.rs
  misc/multiaddr/tests/lib.rs
  protocols/identify/src/id_transport.rs
  protocols/identify/src/protocol.rs
  protocols/kad/src/behaviour/test.rs
  protocols/kad/src/protocol.rs
  protocols/observed/src/lib.rs
  src/bandwidth.rs
  src/lib.rs
  transports/dns/src/lib.rs
  transports/ratelimit/src/lib.rs
  transports/tcp/src/lib.rs
  transports/uds/src/lib.rs
  transports/websocket/src/browser.rs
  transports/websocket/src/desktop.rs
Labels: in progress

#1068 Fix `multiaddr::util::BytesWriter`.
  misc/multiaddr/src/util.rs
  misc/multiaddr/tests/lib.rs
Labels: in progress

#1069 Update to yamux 0.2.0
  muxers/yamux/Cargo.toml
  muxers/yamux/src/lib.rs
Labels: in progress

#1065 swarm: ban connections based on peerid
  core/src/swarm/swarm.rs
Labels: in progress

#1074 Fix CircleCI build
  .circleci/config.yml
Labels: in progress

#1072 Fix connection & handler shutdown when using `KeepAlive::Now`.
  core/src/protocols_handler/node_handler.rs
  core/tests/raw_swarm_simult.rs
  protocols/identify/src/identify.rs
Labels: changelog, in progress

#1067 Remove libp2p-ping keep-alive functionality.
  core/src/protocols_handler/mod.rs
  protocols/ping/Cargo.toml
  protocols/ping/src/handler.rs
  protocols/ping/src/lib.rs
Labels: in progress

#1077 Small addendum to #1072.
  core/src/protocols_handler/mod.rs
  core/src/protocols_handler/node_handler.rs
Labels: in progress

#1073 &mut self -> &mut Self
  core/src/swarm/swarm.rs
Labels: in progress

#1078 Rename `KeepAlive::Now` and `KeepAlive::Forever`.
  core/src/protocols_handler/dummy.rs
  core/src/protocols_handler/mod.rs
  core/src/protocols_handler/node_handler.rs
  core/src/protocols_handler/one_shot.rs
  core/src/swarm/toggle.rs
  core/tests/raw_swarm_dial_error.rs
  core/tests/raw_swarm_simult.rs
  protocols/identify/src/listen_handler.rs
  protocols/identify/src/periodic_id_handler.rs
  protocols/kad/src/handler.rs
  protocols/ping/src/handler.rs
Labels: in progress

#1081 Bump to 0.7.0
  CHANGELOG.md
  Cargo.toml
  core/Cargo.toml
  misc/core-derive/Cargo.toml
  misc/mdns/Cargo.toml
  misc/multiaddr/Cargo.toml
  misc/multihash/Cargo.toml
  misc/peer-id-generator/Cargo.toml
  muxers/mplex/Cargo.toml
  muxers/yamux/Cargo.toml
  protocols/floodsub/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/kad/Cargo.toml
  protocols/noise/Cargo.toml
  protocols/observed/Cargo.toml
  protocols/ping/Cargo.toml
  protocols/plaintext/Cargo.toml
  protocols/secio/Cargo.toml
  transports/dns/Cargo.toml
  transports/ratelimit/Cargo.toml
  transports/tcp/Cargo.toml
  transports/uds/Cargo.toml
  transports/websocket/Cargo.toml
Labels: in progress

#1079 Add a OneSubstreamMuxer
  core/src/muxing.rs
  core/src/muxing/singleton.rs
Labels: in progress

#1088 Add back simple, optional keep-alive to libp2p-ping.
  examples/ping.rs
  protocols/ping/src/handler.rs
  protocols/ping/tests/ping.rs
Labels: in progress

#1071 Switch to wasm-timer
  Cargo.toml
  core/Cargo.toml
  core/src/protocols_handler/mod.rs
  core/src/protocols_handler/node_handler.rs
  core/src/protocols_handler/one_shot.rs
  core/src/transport/timeout.rs
  core/tests/raw_swarm_simult.rs
  misc/mdns/Cargo.toml
  misc/mdns/src/behaviour.rs
  misc/mdns/src/service.rs
  protocols/identify/Cargo.toml
  protocols/identify/src/periodic_id_handler.rs
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour.rs
  protocols/kad/src/handler.rs
  protocols/kad/src/query.rs
  protocols/ping/Cargo.toml
  protocols/ping/src/handler.rs
  protocols/ping/src/protocol.rs
  src/bandwidth.rs
Labels: in progress

#1070 Add wasm-ext-transport
  Cargo.toml
  transports/wasm-ext/Cargo.toml
  transports/wasm-ext/src/lib.rs
Labels: changelog, in progress

#1083 muxing: adds an error type to streammuxer
  core/src/either.rs
  core/src/muxing.rs
  core/src/muxing/singleton.rs
  core/src/nodes/node.rs
  core/src/tests/dummy_muxer.rs
  muxers/mplex/src/lib.rs
  muxers/yamux/src/lib.rs
  protocols/identify/src/id_transport.rs
  protocols/identify/src/identify.rs
  protocols/ping/tests/ping.rs
  src/lib.rs
Labels: changelog

#1095 Replace PeerId with Multihash for interface consistency
  protocols/kad/src/behaviour.rs
Labels: changelog, in progress

#1092 remove direct dependencies on multiaddr
  transports/dns/Cargo.toml
  transports/dns/src/lib.rs
  transports/tcp/Cargo.toml
  transports/tcp/src/lib.rs
  transports/uds/Cargo.toml
  transports/uds/src/lib.rs
  transports/websocket/Cargo.toml
  transports/websocket/src/browser.rs
  transports/websocket/src/desktop.rs
Labels: in progress
