Repository libp2p/rust-libp2p, pull requests merged in 2019-06, with the labels that each got.

#1149 Add sign/verify raw_hash to secp256k1
  core/src/identity/secp256k1.rs
Labels: pr-queued-to-merge

#1144 Kademlia Records
  examples/ipfs-kad.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/behaviour/test.rs
  protocols/kad/src/handler.rs
  protocols/kad/src/lib.rs
  protocols/kad/src/protocol.rs
  protocols/kad/src/record.rs
  protocols/kad/src/write.rs
Labels: in progress

#1177 PollParameters is now a trait
  core/src/swarm.rs
  core/src/swarm/behaviour.rs
  core/src/swarm/registry.rs
  core/src/swarm/swarm.rs
  core/src/swarm/toggle.rs
  misc/core-derive/src/lib.rs
  misc/mdns/src/behaviour.rs
  protocols/floodsub/src/layer.rs
  protocols/identify/src/identify.rs
  protocols/kad/src/behaviour.rs
  protocols/ping/src/lib.rs
Labels: changelog
