Repository libp2p/rust-libp2p, pull requests merged in 2020-09, with the labels that each got.

#1685 [noise] Remove (by default) support for receiving legacy handshakes.
  CHANGELOG.md
  Cargo.toml
  protocols/noise/CHANGELOG.md
  protocols/noise/Cargo.toml
  protocols/noise/src/io/handshake.rs
  protocols/noise/src/lib.rs
Labels: priority:oneday

#1731 Add back the LRU cache to `Throttled`.
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/throttled.rs
  protocols/request-response/tests/ping.rs
Labels: pr-queued-to-merge

#1732 [core] Simplify accepting incoming connections.
  core/CHANGELOG.md
  core/src/network.rs
  core/src/network/event.rs
  core/tests/network_dial_error.rs
  swarm/src/lib.rs
Labels: pr-queued-to-merge

#1733 yamux-0.5.0 upgrade
  CHANGELOG.md
  muxers/yamux/CHANGELOG.md
  muxers/yamux/Cargo.toml
Labels: pr-queued-to-merge

#1769 [mplex] Refactoring with Patches
  Cargo.toml
  muxers/mplex/CHANGELOG.md
  muxers/mplex/Cargo.toml
  muxers/mplex/src/codec.rs
  muxers/mplex/src/config.rs
  muxers/mplex/src/io.rs
  muxers/mplex/src/lib.rs
Labels: category:multiplexing, changelog, pr-queued-to-merge

#1770 [ping] Add missing flush after write.
  protocols/ping/CHANGELOG.md
  protocols/ping/Cargo.toml
  protocols/ping/src/protocol.rs
  protocols/ping/tests/ping.rs
Labels: pr-queued-to-merge
