Repository libp2p/rust-libp2p, pull requests merged in 2022-11, with the labels that each got.

#3070 protocols/gossipsub: Make use of `prost-codec`
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/error.rs
  protocols/gossipsub/src/protocol.rs
Labels: send-it

#3077 *: Link to libp2p/specs in doc comments
  core/src/peer_id.rs
  muxers/mplex/src/lib.rs
  muxers/yamux/src/lib.rs
  protocols/autonat/src/lib.rs
  protocols/floodsub/src/lib.rs
  protocols/gossipsub/src/lib.rs
  protocols/kad/src/lib.rs
  protocols/mdns/src/lib.rs
  protocols/relay/src/lib.rs
  protocols/relay/src/v2.rs
  protocols/rendezvous/src/lib.rs
  src/tutorials.rs
  transports/dns/src/lib.rs
  transports/plaintext/src/lib.rs
  transports/pnet/src/lib.rs
Labels: send-it

#2995 protocols/identify: Change default cache_size of Config to 100
  Cargo.toml
  protocols/identify/CHANGELOG.md
  protocols/identify/src/behaviour.rs
Labels: send-it

#3106 *: Fix newly raised clippy warnings
  core/src/identity/ecdsa.rs
  examples/chat-tokio.rs
  examples/chat.rs
  examples/distributed-key-value-store.rs
  examples/file-sharing.rs
  examples/gossipsub-chat.rs
  examples/ipfs-kad.rs
  examples/ipfs-private.rs
  examples/mdns-passive-discovery.rs
  examples/ping.rs
  muxers/mplex/src/codec.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/peer_score.rs
  protocols/gossipsub/src/peer_score/tests.rs
  protocols/gossipsub/src/subscription_filter.rs
  protocols/kad/src/kbucket/key.rs
  protocols/kad/src/query/peers/closest/disjoint.rs
  protocols/relay/src/v2/relay.rs
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/src/server.rs
Labels: send-it

#3055 swarm-derive: Add `prelude` configuration option to `NetworkBehaviour` macro
  CHANGELOG.md
  Cargo.toml
  examples/chat-tokio.rs
  examples/chat.rs
  examples/distributed-key-value-store.rs
  examples/file-sharing.rs
  examples/gossipsub-chat.rs
  examples/ipfs-private.rs
  examples/ping.rs
  misc/metrics/examples/metrics/main.rs
  protocols/autonat/examples/autonat_client.rs
  protocols/autonat/examples/autonat_server.rs
  protocols/dcutr/examples/dcutr.rs
  protocols/dcutr/tests/lib.rs
  protocols/ping/tests/ping.rs
  protocols/relay/examples/relay_v2.rs
  protocols/relay/tests/v2.rs
  protocols/rendezvous/examples/discover.rs
  protocols/rendezvous/examples/register.rs
  protocols/rendezvous/examples/register_with_identify.rs
  protocols/rendezvous/examples/rendezvous_point.rs
  protocols/rendezvous/tests/rendezvous.rs
  src/lib.rs
  swarm-derive/CHANGELOG.md
  swarm-derive/Cargo.toml
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/behaviour.rs
  swarm/src/lib.rs
  swarm/tests/swarm_derive.rs
Labels: send-it

#3114 protocols/kad: Expose `NoKnownPeers`
  protocols/kad/src/lib.rs
Labels: send-it

#3110 *: Remove lazy_static in favor of once_cell
  Cargo.toml
  core/Cargo.toml
  core/src/transport/memory.rs
  transports/noise/Cargo.toml
  transports/noise/src/protocol.rs
  transports/noise/src/protocol/x25519.rs
Labels: send-it

#3108 test: Remove `dialer_can_receive` stream muxer test
  muxers/mplex/tests/compliance.rs
  muxers/test-harness/src/lib.rs
  muxers/yamux/tests/compliance.rs
Labels: send-it

#3102 refactor(mdns): Parse messages using `trust-dns-proto` instead of `dns-parse`
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour/iface/dns.rs
  protocols/mdns/src/behaviour/iface/query.rs
  protocols/mdns/src/lib.rs
Labels: send-it

#3084 docs(core): Document byte format of `PeerId`
  core/src/peer_id.rs
Labels: send-it

#3071 muxers/yamux: Mitigation of unnecessary stream drops
  muxers/yamux/CHANGELOG.md
  muxers/yamux/Cargo.toml
  muxers/yamux/src/lib.rs
Labels: send-it

#3113 core: Expose `peer_id::ParseError`
  core/src/lib.rs
Labels: send-it

#3101 transports/tcp: Update if-watch to `v3.0.0`
  transports/tcp/CHANGELOG.md
  transports/tcp/Cargo.toml
  transports/tcp/src/lib.rs
  transports/tcp/src/provider.rs
  transports/tcp/src/provider/async_io.rs
  transports/tcp/src/provider/tokio.rs
Labels: send-it

#3097 feat(swarm): Make executor for connection tasks explicit
  Cargo.toml
  core/CHANGELOG.md
  core/src/lib.rs
  examples/chat-tokio.rs
  examples/chat.rs
  examples/distributed-key-value-store.rs
  examples/file-sharing.rs
  examples/gossipsub-chat.rs
  examples/ipfs-kad.rs
  examples/ipfs-private.rs
  examples/mdns-passive-discovery.rs
  examples/ping.rs
  misc/metrics/examples/metrics/main.rs
  misc/multistream-select/tests/transport.rs
  protocols/autonat/examples/autonat_client.rs
  protocols/autonat/examples/autonat_server.rs
  protocols/autonat/tests/test_client.rs
  protocols/autonat/tests/test_server.rs
  protocols/dcutr/examples/dcutr.rs
  protocols/dcutr/tests/lib.rs
  protocols/gossipsub/tests/smoke.rs
  protocols/identify/examples/identify.rs
  protocols/identify/src/behaviour.rs
  protocols/kad/src/behaviour/test.rs
  protocols/mdns/tests/use-async-std.rs
  protocols/mdns/tests/use-tokio.rs
  protocols/ping/tests/ping.rs
  protocols/relay/examples/relay_v2.rs
  protocols/relay/tests/v2.rs
  protocols/rendezvous/examples/discover.rs
  protocols/rendezvous/examples/register.rs
  protocols/rendezvous/examples/register_with_identify.rs
  protocols/rendezvous/examples/rendezvous_point.rs
  protocols/rendezvous/tests/harness.rs
  protocols/request-response/tests/ping.rs
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/connection/pool.rs
  swarm/src/executor.rs
  swarm/src/lib.rs
  transports/tls/tests/smoke.rs
Labels: send-it

#2982 misc/metrics: Add `protocols` label to address-specific metrics
  misc/metrics/CHANGELOG.md
  misc/metrics/examples/metrics/main.rs
  misc/metrics/src/identify.rs
  misc/metrics/src/lib.rs
  misc/metrics/src/protocol_stack.rs
  misc/metrics/src/swarm.rs
Labels: send-it

#2622 feat: Add WebRTC transport
  Cargo.toml
  misc/prost-codec/CHANGELOG.md
  misc/prost-codec/Cargo.toml
  misc/prost-codec/src/lib.rs
  src/lib.rs
  transports/webrtc/Cargo.toml
  transports/webrtc/build.rs
  transports/webrtc/examples/listen_ping.rs
  transports/webrtc/src/lib.rs
  transports/webrtc/src/message.proto
  transports/webrtc/src/tokio/certificate.rs
  transports/webrtc/src/tokio/connection.rs
  transports/webrtc/src/tokio/error.rs
  transports/webrtc/src/tokio/fingerprint.rs
  transports/webrtc/src/tokio/mod.rs
  transports/webrtc/src/tokio/req_res_chan.rs
  transports/webrtc/src/tokio/sdp.rs
  transports/webrtc/src/tokio/substream.rs
  transports/webrtc/src/tokio/substream/drop_listener.rs
  transports/webrtc/src/tokio/substream/framed_dc.rs
  transports/webrtc/src/tokio/substream/state.rs
  transports/webrtc/src/tokio/transport.rs
  transports/webrtc/src/tokio/udp_mux.rs
  transports/webrtc/src/tokio/upgrade.rs
  transports/webrtc/src/tokio/upgrade/noise.rs
  transports/webrtc/tests/smoke.rs
Labels: difficulty:hard, in progress, send-it

#3011 swarm/behaviour: Replace `inject_*` with `on_event`
  protocols/autonat/CHANGELOG.md
  protocols/autonat/src/behaviour.rs
  protocols/dcutr/CHANGELOG.md
  protocols/dcutr/src/behaviour.rs
  protocols/floodsub/CHANGELOG.md
  protocols/floodsub/src/layer.rs
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/identify/CHANGELOG.md
  protocols/identify/src/behaviour.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/behaviour/test.rs
  protocols/mdns/CHANGELOG.md
  protocols/mdns/src/behaviour.rs
  protocols/ping/CHANGELOG.md
  protocols/ping/src/lib.rs
  protocols/relay/CHANGELOG.md
  protocols/relay/src/v2/client.rs
  protocols/relay/src/v2/relay.rs
  protocols/rendezvous/CHANGELOG.md
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/src/server.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/src/lib.rs
  swarm-derive/CHANGELOG.md
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/behaviour/either.rs
  swarm/src/behaviour/toggle.rs
  swarm/src/dummy.rs
  swarm/src/handler/either.rs
  swarm/src/keep_alive.rs
  swarm/src/lib.rs
  swarm/src/test.rs
  swarm/tests/swarm_derive.rs
Labels: send-it

#3131 fix: Allow `libp2p-mdns` to compile without feature-flags
  protocols/mdns/Cargo.toml
Labels: send-it

#3085 swarm/handler: replace inject_* methods
  protocols/dcutr/CHANGELOG.md
  protocols/dcutr/src/handler/direct.rs
  protocols/dcutr/src/handler/relayed.rs
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/handler.rs
  protocols/identify/CHANGELOG.md
  protocols/identify/src/handler.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/src/handler.rs
  protocols/ping/CHANGELOG.md
  protocols/ping/src/handler.rs
  protocols/relay/CHANGELOG.md
  protocols/relay/src/v2/client/handler.rs
  protocols/relay/src/v2/relay/handler.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/src/handler.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour/toggle.rs
  swarm/src/connection.rs
  swarm/src/connection/pool/task.rs
  swarm/src/dummy.rs
  swarm/src/handler.rs
  swarm/src/handler/either.rs
  swarm/src/handler/map_in.rs
  swarm/src/handler/map_out.rs
  swarm/src/handler/multi.rs
  swarm/src/handler/one_shot.rs
  swarm/src/handler/pending.rs
  swarm/src/handler/select.rs
  swarm/src/keep_alive.rs
Labels: send-it

#3096 mdns: update if-watch to 3.0.0
  examples/chat-tokio.rs
  examples/chat.rs
  examples/distributed-key-value-store.rs
  examples/gossipsub-chat.rs
  examples/mdns-passive-discovery.rs
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour.rs
  protocols/mdns/src/behaviour/iface.rs
  protocols/mdns/src/lib.rs
  protocols/mdns/tests/use-async-std.rs
  protocols/mdns/tests/use-tokio.rs
Labels: send-it

#3142 fix(webrtc): Don't emit addresses from other interfaces
  transports/webrtc/Cargo.toml
  transports/webrtc/src/tokio/transport.rs
Labels: send-it

#3129 chore(ci): Add `--locked` flag to `cargo install` step
  .github/workflows/ci.yml
Labels: send-it

#2972 feat: Better error reporting when features are disabled
  core/CHANGELOG.md
  core/Cargo.toml
  core/src/identity.rs
  core/src/identity/ecdsa.rs
  core/src/identity/ed25519.rs
  core/src/identity/error.rs
  core/src/identity/rsa.rs
  core/src/identity/secp256k1.rs
  core/src/upgrade/error.rs
  examples/ipfs-kad.rs
  swarm/src/lib.rs
  transports/noise/CHANGELOG.md
  transports/noise/Cargo.toml
  transports/noise/src/error.rs
  transports/noise/src/io/framed.rs
  transports/noise/src/io/handshake.rs
  transports/noise/src/lib.rs
  transports/noise/src/protocol/x25519.rs
  transports/noise/src/protocol/x25519_spec.rs
  transports/noise/tests/smoke.rs
Labels: send-it

#3132 docs(swarm): Reword `Swarm` top-level doc string
  swarm/src/lib.rs
Labels: send-it

#3155 fix(swarm): Make executors pub and add convenience constructors for SwarmBuilder
  swarm/src/executor.rs
  swarm/src/lib.rs
Labels: send-it

#3083 chore: Enforce conventional commit PR title
  .github/dependabot.yml
  .github/mergify.yml
Labels: send-it

#3115 feat(swarm): Add `wasm-bindgen` executor
  Cargo.toml
  swarm/Cargo.toml
  swarm/src/executor.rs
  swarm/src/lib.rs
Labels: send-it

#2712 protocols/kad: Improve options to efficiently retrieve
  examples/distributed-key-value-store.rs
  examples/file-sharing.rs
  examples/ipfs-kad.rs
  misc/metrics/CHANGELOG.md
  misc/metrics/src/kad.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/behaviour/test.rs
  protocols/kad/src/lib.rs
Labels: difficulty:moderate, send-it

#3164 fix(quic): allow closing stream after remote dropped it
  transports/quic/src/connection.rs
  transports/quic/src/connection/substream.rs
  transports/quic/tests/smoke.rs
Labels: send-it

#3163 chore: Prepare rust-libp2p v0.50.0 release
  CHANGELOG.md
  Cargo.toml
  core/CHANGELOG.md
  misc/metrics/CHANGELOG.md
  misc/prost-codec/CHANGELOG.md
  muxers/mplex/CHANGELOG.md
  muxers/yamux/CHANGELOG.md
  protocols/autonat/CHANGELOG.md
  protocols/dcutr/CHANGELOG.md
  protocols/floodsub/CHANGELOG.md
  protocols/gossipsub/CHANGELOG.md
  protocols/identify/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  protocols/mdns/CHANGELOG.md
  protocols/ping/CHANGELOG.md
  protocols/relay/CHANGELOG.md
  protocols/rendezvous/CHANGELOG.md
  protocols/request-response/CHANGELOG.md
  swarm-derive/CHANGELOG.md
  swarm/CHANGELOG.md
  transports/deflate/CHANGELOG.md
  transports/dns/CHANGELOG.md
  transports/noise/CHANGELOG.md
  transports/plaintext/CHANGELOG.md
  transports/quic/CHANGELOG.md
  transports/tcp/CHANGELOG.md
  transports/tls/CHANGELOG.md
  transports/uds/CHANGELOG.md
  transports/wasm-ext/CHANGELOG.md
  transports/webrtc/CHANGELOG.md
  transports/webrtc/Cargo.toml
  transports/websocket/CHANGELOG.md
Labels: send-it
