Repository libp2p/rust-libp2p, pull requests merged in 2023-10, with the labels that each got.

#4574 refactor(examples): change autonat example from async-std to tokio
  Cargo.lock
  examples/autonat/Cargo.toml
  examples/autonat/src/bin/autonat_client.rs
  examples/autonat/src/bin/autonat_server.rs
Labels: send-it

#4554 feat(quic): support stateless resets
  Cargo.lock
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/ed25519.rs
  identity/src/keypair.rs
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/quic/src/config.rs
Labels: send-it

#4582 fix(identity): address clippy lint
  identity/src/keypair.rs
Labels: send-it, trivial

#4583 chore(identity): release version 0.2.4
  Cargo.lock
  Cargo.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
Labels: send-it, trivial

#4570 refactor(examples): change ping from async-std to tokio
  Cargo.lock
  examples/ping/Cargo.toml
  examples/ping/src/main.rs
Labels: send-it

#4580 refactor(examples): remove `#[behaviour(to_swarm = "Event")]`
  examples/dcutr/src/main.rs
  examples/distributed-key-value-store/src/main.rs
  examples/file-sharing/src/network.rs
  protocols/dcutr/tests/lib.rs
Labels: send-it

#4591 refactor(examples): change ipfs-private from async-std to tokio
  Cargo.lock
  examples/ipfs-private/Cargo.toml
  examples/ipfs-private/src/main.rs
Labels: send-it

#4590 refactor(examples): change ipfs-kad from async-std to tokio
  Cargo.lock
  examples/ipfs-kad/Cargo.toml
  examples/ipfs-kad/src/main.rs
Labels: send-it

#4593 ci: create dependency cache layer of interop tests
  .github/workflows/interop-test.yml
  interop-tests/Dockerfile.chromium
  interop-tests/Dockerfile.native
Labels: send-it, trivial

#4602 fix: remove redundant intra-doc link
  core/src/transport.rs
  libp2p/src/lib.rs
  misc/connection-limits/src/lib.rs
  misc/memory-connection-limits/src/lib.rs
  misc/multistream-select/src/lib.rs
  swarm/src/behaviour.rs
  swarm/src/connection.rs
  swarm/src/connection/pool.rs
  swarm/src/lib.rs
Labels: send-it, trivial

#4603 deps: upgrade `cargo semver-checks` to `v0.24`
  .github/workflows/ci.yml
Labels: send-it, trivial

#4589 fix(identity): correctly follow extract-expand for HKDF
  Cargo.lock
  Cargo.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/keypair.rs
  identity/tests/keypair_api.rs
Labels: send-it

#4604 fix(interop): only write to cache if we have credentials
  .github/workflows/interop-test.yml
  scripts/build-interop-image.sh
Labels: send-it, trivial

#4599 chore(upnp, webrtc): add missing docs.rs metadata
  protocols/upnp/Cargo.toml
  transports/webrtc/Cargo.toml
  transports/webrtc/src/lib.rs
Labels: send-it

#4560 feat: change `md` issue templates into `yml` forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: send-it

#4567 docs: add pk records insertion example
  .github/workflows/ci.yml
  Cargo.lock
  examples/ipfs-kad/Cargo.toml
  examples/ipfs-kad/README.md
  examples/ipfs-kad/src/main.rs
Labels: send-it

#4102 feat(websocket): add WebSocket for WASM environments
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  interop-tests/Cargo.toml
  interop-tests/chromium-ping-version.json
  interop-tests/src/arch.rs
  interop-tests/src/bin/config/mod.rs
  interop-tests/src/bin/native_ping.rs
  interop-tests/src/bin/wasm_ping.rs
  interop-tests/src/lib.rs
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  transports/websocket-websys/CHANGELOG.md
  transports/websocket-websys/Cargo.toml
  transports/websocket-websys/src/lib.rs
Labels: send-it

#4619 fix: don't push `rust-libp2p-server` image for dependabot PRs
  .github/workflows/docker-image.yml
Labels: send-it, trivial

#4622 fix(server): remove `support_draft_29`
  misc/server/src/main.rs
Labels: send-it, trivial

#4594 ci: use new "transport-interop" action
  .github/workflows/interop-test.yml
Labels: send-it

#4634 fix(kad): rewrite tests to be less flaky
  protocols/kad/tests/client_mode.rs
Labels: send-it, trivial

#4630 docs: fix misc. errors around changelogs and manifests
  Cargo.lock
  Cargo.toml
  misc/server/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/websocket-websys/CHANGELOG.md
Labels: send-it, trivial

#4631 refactor: make debug-print of `StreamProtocol` more concise
  swarm/CHANGELOG.md
  swarm/src/stream_protocol.rs
Labels: send-it, trivial

#4633 refactor(kad): delete unused code
  protocols/kad/src/jobs.rs
  protocols/kad/src/kbucket/bucket.rs
  protocols/kad/src/kbucket/entry.rs
  protocols/kad/src/lib.rs
  protocols/kad/src/query.rs
  protocols/kad/src/query/peers/closest.rs
  protocols/kad/src/query/peers/closest/disjoint.rs
  protocols/kad/src/query/peers/fixed.rs
Labels: send-it

#4640 fix(quic): delete flaky `dial_failure` test
  transports/quic/tests/smoke.rs
Labels: send-it

#4626 fix(libp2p): add shortcut `with_tcp(...).with_bandwidth_logging()`
  libp2p/src/builder.rs
  libp2p/src/builder/phase/quic.rs
Labels: send-it

#4620 ci: ensure `Cargo.toml` and `CHANGELOG` of published crates are updated
  .github/workflows/ci.yml
  scripts/ensure-version-bump-and-changelog.sh
Labels: send-it

#4639 fix(kad): actually report unsupported protocol
  protocols/kad/CHANGELOG.md
  protocols/kad/src/handler.rs
Labels: send-it

#4629 feat(rendezous): refresh registration on change to external addresses
  Cargo.lock
  Cargo.toml
  protocols/rendezvous/CHANGELOG.md
  protocols/rendezvous/Cargo.toml
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/tests/rendezvous.rs
Labels: send-it

#4648 feat(gossipsub): deprecate `Config::idle_timeout`
  Cargo.lock
  Cargo.toml
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/config.rs
Labels: send-it

#4652 chore: activate `clippy::unnecessary_wraps` lint
  Cargo.toml
Labels: send-it, trivial

#4654 ci: run clippy on all targets
  .github/workflows/ci.yml
  protocols/kad/CHANGELOG.md
  protocols/kad/src/handler.rs
Labels: send-it, trivial

#4658 ci: don't run changelog check on chores and refactor PRs
  .github/workflows/ci.yml
  protocols/kad/CHANGELOG.md
Labels: send-it, trivial

#4655 chore(perf): remove unused module
  protocols/perf/src/client/behaviour.rs
  protocols/perf/src/client/handler.rs
  protocols/perf/src/server/behaviour.rs
  protocols/perf/src/server/handler.rs
Labels: send-it

#4657 deps(noise): update `x25519-dalek` to 2.0.0
  Cargo.lock
  Cargo.toml
  transports/noise/CHANGELOG.md
  transports/noise/Cargo.toml
Labels: send-it

#4656 feat(swarm): deprecate `KeepAlive::Until`
  Cargo.lock
  Cargo.toml
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/handler.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/src/handler.rs
  protocols/relay/CHANGELOG.md
  protocols/relay/Cargo.toml
  protocols/relay/src/behaviour/handler.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/handler.rs
  swarm/CHANGELOG.md
  swarm/src/connection.rs
  swarm/src/handler.rs
  swarm/src/handler/one_shot.rs
Labels: send-it

#4653 chore: apply clippy lints to public API
  Cargo.lock
  Cargo.toml
  clippy.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/lib.rs
  identity/src/peer_id.rs
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
  transports/pnet/CHANGELOG.md
  transports/pnet/Cargo.toml
  transports/pnet/src/lib.rs
  transports/webrtc-websys/CHANGELOG.md
  transports/webrtc-websys/Cargo.toml
  transports/webrtc-websys/src/connection.rs
  transports/webrtc-websys/src/error.rs
Labels: send-it

#4670 ci: don't require changelog entries for `docs` and `deps`
  .github/workflows/ci.yml
Labels: send-it, trivial

#4605 refactor: use `cargo chef` for `rust-libp2p-server` docker build
  .github/workflows/docker-image.yml
  misc/server/Dockerfile
Labels: send-it

#4645 fix(kad): re-export `NodeStatus`
  protocols/kad/CHANGELOG.md
  protocols/kad/src/kbucket.rs
  protocols/kad/src/lib.rs
Labels: send-it

#4673 ci: allow opt-out of changelog lint for internal changes
  .github/workflows/ci.yml
  docs/maintainer-handbook.md
Labels: send-it, trivial

#4680 feat(swarm): deprecated `keep_alive_timeout` from `OneShotHandlerConfig`
  swarm/CHANGELOG.md
  swarm/src/handler/one_shot.rs
Labels: send-it

#4681 refactor(examples): add rendezvous point fixed keypair
  examples/rendezvous/src/main.rs
Labels: send-it

#4682 docs(readme): add homestar as notable user
  README.md
Labels: send-it

#4349 feat(identity): make rand optional
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/ecdsa.rs
  identity/src/ed25519.rs
  identity/src/keypair.rs
  identity/src/peer_id.rs
  identity/src/secp256k1.rs
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  misc/metrics/Cargo.toml
  muxers/mplex/Cargo.toml
  protocols/gossipsub/Cargo.toml
  protocols/kad/Cargo.toml
  protocols/perf/Cargo.toml
  protocols/relay/Cargo.toml
  swarm-test/Cargo.toml
  transports/dns/Cargo.toml
  transports/noise/Cargo.toml
  transports/plaintext/Cargo.toml
  transports/pnet/Cargo.toml
  transports/quic/Cargo.toml
  transports/tcp/Cargo.toml
  transports/tls/Cargo.toml
  transports/webrtc/Cargo.toml
  transports/websocket-websys/Cargo.toml
  transports/websocket/Cargo.toml
  wasm-tests/webtransport-tests/Cargo.toml
Labels: send-it, internal-change

#4644 fix(swarm): prevent overflow in keep-alive computation
  swarm/CHANGELOG.md
  swarm/src/connection.rs
  swarm/src/handler.rs
Labels: send-it

#4029 feat(request-response): deprecate `Config::set_connection_keep_alive`
  protocols/perf/src/bin/perf.rs
  protocols/perf/src/client.rs
  protocols/perf/src/server.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/src/lib.rs
Labels: send-it, internal-change

#4672 fix(SwarmBuilder): prioritize relay, then websocket, then any other
  libp2p/src/builder.rs
  libp2p/src/builder/phase/dns.rs
  libp2p/src/builder/phase/other_transport.rs
  libp2p/src/builder/phase/quic.rs
  libp2p/src/builder/phase/relay.rs
  libp2p/src/builder/phase/tcp.rs
  libp2p/src/builder/phase/websocket.rs
Labels: send-it, internal-change

#4625 chore: prepare libp2p v0.52.4
  libp2p/CHANGELOG.md
  protocols/gossipsub/CHANGELOG.md
  protocols/identify/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  protocols/relay/CHANGELOG.md
  protocols/rendezvous/CHANGELOG.md
  protocols/request-response/CHANGELOG.md
  protocols/upnp/CHANGELOG.md
  swarm/CHANGELOG.md
  transports/deflate/CHANGELOG.md
  transports/dns/CHANGELOG.md
  transports/plaintext/CHANGELOG.md
  transports/pnet/CHANGELOG.md
  transports/quic/CHANGELOG.md
  transports/webrtc-websys/CHANGELOG.md
  transports/websocket-websys/CHANGELOG.md
Labels: send-it

#4683 chore(tcp): release v0.40.1
  Cargo.lock
  Cargo.toml
  transports/tcp/CHANGELOG.md
  transports/tcp/Cargo.toml
Labels: send-it, trivial

#4685 chore: open merge window for next breaking release
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  examples/autonat/Cargo.toml
  examples/browser-webrtc/Cargo.toml
  examples/chat/Cargo.toml
  examples/dcutr/Cargo.toml
  examples/distributed-key-value-store/Cargo.toml
  examples/file-sharing/Cargo.toml
  examples/identify/Cargo.toml
  examples/ipfs-kad/Cargo.toml
  examples/ipfs-private/Cargo.toml
  examples/metrics/Cargo.toml
  examples/ping/Cargo.toml
  examples/relay-server/Cargo.toml
  examples/rendezvous/Cargo.toml
  examples/upnp/Cargo.toml
  interop-tests/Cargo.toml
  libp2p/Cargo.toml
  misc/allow-block-list/Cargo.toml
  misc/connection-limits/Cargo.toml
  misc/keygen/Cargo.toml
  misc/memory-connection-limits/Cargo.toml
  misc/metrics/Cargo.toml
  misc/quickcheck-ext/Cargo.toml
  muxers/mplex/Cargo.toml
  muxers/test-harness/Cargo.toml
  muxers/yamux/Cargo.toml
  protocols/autonat/Cargo.toml
  protocols/dcutr/Cargo.toml
  protocols/floodsub/Cargo.toml
  protocols/gossipsub/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/kad/Cargo.toml
  protocols/mdns/Cargo.toml
  protocols/ping/Cargo.toml
  protocols/relay/Cargo.toml
  protocols/rendezvous/Cargo.toml
  protocols/request-response/Cargo.toml
  protocols/upnp/Cargo.toml
  swarm-derive/Cargo.toml
  swarm-test/Cargo.toml
  swarm/Cargo.toml
  transports/deflate/Cargo.toml
  transports/dns/Cargo.toml
  transports/noise/Cargo.toml
  transports/plaintext/Cargo.toml
  transports/pnet/Cargo.toml
  transports/quic/Cargo.toml
  transports/tcp/Cargo.toml
  transports/tls/Cargo.toml
  transports/uds/Cargo.toml
  transports/websocket-websys/Cargo.toml
  transports/websocket/Cargo.toml
  transports/webtransport-websys/Cargo.toml
  wasm-tests/webtransport-tests/Cargo.toml
Labels: internal-change

#4690 chore: add new header to changelog of each crate
  Cargo.toml
  core/CHANGELOG.md
  libp2p/CHANGELOG.md
  misc/allow-block-list/CHANGELOG.md
  misc/connection-limits/CHANGELOG.md
  misc/memory-connection-limits/CHANGELOG.md
  misc/metrics/CHANGELOG.md
  muxers/mplex/CHANGELOG.md
  muxers/yamux/CHANGELOG.md
  protocols/autonat/CHANGELOG.md
  protocols/dcutr/CHANGELOG.md
  protocols/floodsub/CHANGELOG.md
  protocols/gossipsub/CHANGELOG.md
  protocols/identify/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  protocols/mdns/CHANGELOG.md
  protocols/ping/CHANGELOG.md
  protocols/relay/CHANGELOG.md
  protocols/rendezvous/CHANGELOG.md
  protocols/request-response/CHANGELOG.md
  protocols/upnp/CHANGELOG.md
  scripts/add-changelog-header.sh
  swarm-derive/CHANGELOG.md
  swarm-test/CHANGELOG.md
  swarm/CHANGELOG.md
  transports/deflate/CHANGELOG.md
  transports/dns/CHANGELOG.md
  transports/noise/CHANGELOG.md
  transports/plaintext/CHANGELOG.md
  transports/pnet/CHANGELOG.md
  transports/quic/CHANGELOG.md
  transports/tcp/CHANGELOG.md
  transports/tls/CHANGELOG.md
  transports/uds/CHANGELOG.md
  transports/websocket-websys/CHANGELOG.md
  transports/websocket/CHANGELOG.md
  transports/webtransport-websys/CHANGELOG.md
Labels: send-it, trivial

#4445 feat(gossipsub)!: return typed error from config builder
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/config.rs
  protocols/gossipsub/src/error.rs
  protocols/gossipsub/src/lib.rs
Labels: send-it

#4464 feat(dns): make `{tokio,async_std}::Transport::custom` infallible
  transports/dns/CHANGELOG.md
  transports/dns/src/lib.rs
Labels: send-it

#4677 feat(swarm): remove `KeepAlive::Until` from `OneshotHandler`
  swarm/CHANGELOG.md
  swarm/src/handler/one_shot.rs
Labels: send-it

#4642 feat(gossipsub): remove `KeepAlive::Until`
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/config.rs
  protocols/gossipsub/src/handler.rs
Labels: send-it

#4558 feat(dcutr): add `ConnectionId` to upgrade success/failed events
  misc/metrics/src/dcutr.rs
  protocols/dcutr/CHANGELOG.md
  protocols/dcutr/src/behaviour_impl.rs
  protocols/dcutr/tests/lib.rs
Labels: send-it, internal-change

#4225 feat(swarm): allow both Disconnected and NotDialing condition combined
  misc/connection-limits/src/lib.rs
  misc/memory-connection-limits/tests/max_bytes.rs
  misc/memory-connection-limits/tests/max_percentage.rs
  protocols/kad/src/behaviour.rs
  swarm/CHANGELOG.md
  swarm/src/dial_opts.rs
  swarm/src/lib.rs
Labels: send-it, internal-change

#4676 refactor(relay): remove `KeepAlive::Until`
  protocols/relay/CHANGELOG.md
  protocols/relay/src/behaviour/handler.rs
Labels: send-it

#4693 chore(multistream-select): replace `futures_ringbuf` with TCP
  misc/multistream-select/src/dialer_select.rs
  misc/multistream-select/src/lib.rs
  misc/multistream-select/src/listener_select.rs
  misc/multistream-select/tests/dialer_select.rs
Labels: send-it, trivial

#4679 feat(request-response): remove `Config::set_connection_keep_alive`
  protocols/rendezvous/tests/rendezvous.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/src/handler.rs
  protocols/request-response/src/lib.rs
Labels: send-it, internal-change

#4527 feat(identify): include pushed `Info` in `Event::Pushed`
  protocols/identify/CHANGELOG.md
  protocols/identify/src/behaviour.rs
  protocols/identify/src/handler.rs
  protocols/identify/src/protocol.rs
Labels: send-it

#4503 feat(kad): report automatic changes to kad mode
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/behaviour/test.rs
  protocols/kad/tests/client_mode.rs
Labels: send-it

#4623 fix(mdns): move IO off main task
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour.rs
  protocols/mdns/src/behaviour/iface.rs
Labels: send-it

#4285 feat(gossipsub): remove `fast_message_id_fn`
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/config.rs
  protocols/gossipsub/src/lib.rs
  protocols/gossipsub/src/time_cache.rs
  protocols/gossipsub/src/types.rs
Labels: send-it

#4696 refactor(relay): keep connection alive while we are using it
  protocols/relay/src/priv_client/handler.rs
  protocols/relay/tests/lib.rs
Labels: send-it, trivial

#4694 chore: remove deprecated `libp2p-wasm-ext` transport
  Cargo.lock
  Cargo.toml
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  transports/wasm-ext/CHANGELOG.md
  transports/wasm-ext/Cargo.toml
  transports/wasm-ext/src/lib.rs
  transports/wasm-ext/src/websockets.js
Labels: send-it, trivial

#4659 feat(kad): remove deprecated `Config::set_connection_idle_timeout`
  examples/ipfs-kad/src/main.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/behaviour/test.rs
  protocols/kad/src/handler.rs
Labels: send-it

#4704 chore(autonat, gossipsub, relay, quic): implement latest clippy changes
  protocols/autonat/tests/test_server.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/relay/src/priv_client.rs
  transports/quic/src/connection/connecting.rs
Labels: send-it

#4712 deps: bump rcgen to 0.11
  Cargo.lock
  transports/tls/Cargo.toml
  transports/websocket/Cargo.toml
Labels: send-it

#4711 refactor: inline `quicksink` crate
  Cargo.lock
  transports/websocket/Cargo.toml
  transports/websocket/src/framed.rs
  transports/websocket/src/lib.rs
  transports/websocket/src/quicksink.rs
Labels: send-it

#4692 chore: bump MSRV to 1.73
  Cargo.toml
  interop-tests/Dockerfile.chromium
  interop-tests/Dockerfile.native
  libp2p/CHANGELOG.md
  misc/server/Dockerfile
Labels: send-it

#4490 feat(swarm)!: remove `PollParameters`
  misc/allow-block-list/src/lib.rs
  misc/connection-limits/src/lib.rs
  misc/memory-connection-limits/src/lib.rs
  misc/memory-connection-limits/tests/util.rs
  protocols/autonat/src/behaviour.rs
  protocols/autonat/src/behaviour/as_client.rs
  protocols/autonat/src/behaviour/as_server.rs
  protocols/dcutr/src/behaviour_impl.rs
  protocols/floodsub/src/layer.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/identify/src/behaviour.rs
  protocols/kad/src/behaviour.rs
  protocols/mdns/src/behaviour.rs
  protocols/perf/src/client.rs
  protocols/perf/src/server.rs
  protocols/ping/src/lib.rs
  protocols/relay/src/behaviour.rs
  protocols/relay/src/priv_client.rs
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/src/server.rs
  protocols/request-response/src/lib.rs
  protocols/upnp/src/behaviour.rs
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/behaviour/either.rs
  swarm/src/behaviour/toggle.rs
  swarm/src/dummy.rs
  swarm/src/keep_alive.rs
  swarm/src/lib.rs
  swarm/src/test.rs
  swarm/tests/listener.rs
  swarm/tests/swarm_derive.rs
Labels: send-it, internal-change

#4720 docs(libp2p): mention SwarmBuilder::with_swarm_config
  libp2p/src/builder.rs
Labels: send-it, trivial, internal-change

#4714 feat(swarm): deprecate `ConnectionHandlerEvent::Close`
  Cargo.lock
  Cargo.toml
  misc/metrics/src/swarm.rs
  protocols/dcutr/src/handler/relayed.rs
  protocols/gossipsub/src/handler.rs
  protocols/identify/src/handler.rs
  protocols/kad/src/handler.rs
  protocols/ping/src/handler.rs
  protocols/relay/src/behaviour/handler.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/request-response/src/handler.rs
  swarm-test/src/lib.rs
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/behaviour/toggle.rs
  swarm/src/connection.rs
  swarm/src/connection/error.rs
  swarm/src/connection/pool.rs
  swarm/src/connection/pool/task.rs
  swarm/src/dummy.rs
  swarm/src/handler.rs
  swarm/src/handler/either.rs
  swarm/src/handler/map_in.rs
  swarm/src/handler/map_out.rs
  swarm/src/handler/multi.rs
  swarm/src/handler/one_shot.rs
  swarm/src/handler/pending.rs
  swarm/src/handler/select.rs
  swarm/src/keep_alive.rs
  swarm/src/lib.rs
Labels: internal-change

#4715 feat(swarm): don't close connection in `OneShotHandler`
  protocols/floodsub/src/layer.rs
  swarm/CHANGELOG.md
  swarm/src/handler/one_shot.rs
Labels: send-it, internal-change

#4616 feat(futures-bounded): add support for streams
  Cargo.lock
  Cargo.toml
  misc/futures-bounded/CHANGELOG.md
  misc/futures-bounded/Cargo.toml
  misc/futures-bounded/src/futures_map.rs
  misc/futures-bounded/src/futures_set.rs
  misc/futures-bounded/src/lib.rs
  misc/futures-bounded/src/stream_map.rs
  misc/futures-bounded/src/stream_set.rs
  protocols/relay/src/priv_client/handler.rs
Labels: send-it, internal-change

#4700 fix(request-response): don't keep duplicate addresses
  protocols/request-response/CHANGELOG.md
  protocols/request-response/src/lib.rs
Labels: send-it

#4671 fix(swarm): log local peer ID correctly
  swarm/CHANGELOG.md
  swarm/src/lib.rs
Labels: send-it, trivial

#4722 refactor(dcutr): remove dead code
  protocols/dcutr/src/behaviour_impl.rs
  protocols/dcutr/src/handler/relayed.rs
Labels: send-it, trivial

#4723 chore(dcutr): add happy-path logs
  protocols/dcutr/src/behaviour_impl.rs
Labels: send-it, trivial

#4035 chore(kad): remove deprecated module `record`
  examples/distributed-key-value-store/src/main.rs
  examples/file-sharing/src/network.rs
  misc/server/src/behaviour.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/behaviour/test.rs
  protocols/kad/src/handler.rs
  protocols/kad/src/jobs.rs
  protocols/kad/src/kbucket/key.rs
  protocols/kad/src/lib.rs
  protocols/kad/src/protocol.rs
  protocols/kad/src/record.rs
  protocols/kad/src/record/store.rs
  protocols/kad/src/record/store/memory.rs
  swarm/tests/swarm_derive.rs
Labels: send-it

#4595 fix(swarm): keep connections alive while active streams exist
  protocols/dcutr/src/handler/relayed.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/handler.rs
  protocols/identify/src/handler.rs
  protocols/kad/src/handler.rs
  protocols/ping/src/handler.rs
  protocols/relay/src/behaviour/handler.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/request-response/src/handler.rs
  swarm/src/behaviour/toggle.rs
  swarm/src/connection.rs
  swarm/src/dummy.rs
  swarm/src/handler.rs
  swarm/src/handler/either.rs
  swarm/src/handler/map_in.rs
  swarm/src/handler/map_out.rs
  swarm/src/handler/multi.rs
  swarm/src/handler/one_shot.rs
  swarm/src/handler/pending.rs
  swarm/src/handler/select.rs
  swarm/src/keep_alive.rs
  swarm/src/lib.rs
  swarm/src/stream.rs
Labels: send-it, internal-change

#4382 feat(perf): support iperf-style intermittent results
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  protocols/perf/CHANGELOG.md
  protocols/perf/Cargo.toml
  protocols/perf/src/bin/perf.rs
  protocols/perf/src/client.rs
  protocols/perf/src/client/behaviour.rs
  protocols/perf/src/client/handler.rs
  protocols/perf/src/lib.rs
  protocols/perf/src/protocol.rs
  protocols/perf/src/server.rs
  protocols/perf/src/server/behaviour.rs
  protocols/perf/src/server/handler.rs
  protocols/perf/tests/lib.rs
Labels: send-it

#4549 ci: add automated hole-punch tests
  .github/workflows/interop-test.yml
  Cargo.lock
  Cargo.toml
  hole-punching-tests/Cargo.toml
  hole-punching-tests/Dockerfile
  hole-punching-tests/src/main.rs
  hole-punching-tests/version.json
  transports/quic/CHANGELOG.md
  transports/quic/src/hole_punching.rs
  transports/quic/src/transport.rs
Labels: send-it

#4076 feat(swarm): remove `handler` field from `ConnectionClosed` event
  misc/allow-block-list/src/lib.rs
  misc/connection-limits/src/lib.rs
  misc/memory-connection-limits/src/lib.rs
  misc/memory-connection-limits/tests/util.rs
  protocols/autonat/src/behaviour.rs
  protocols/dcutr/src/behaviour_impl.rs
  protocols/floodsub/src/layer.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/identify/src/behaviour.rs
  protocols/kad/src/behaviour.rs
  protocols/mdns/src/behaviour.rs
  protocols/perf/src/client/behaviour.rs
  protocols/perf/src/server/behaviour.rs
  protocols/ping/src/lib.rs
  protocols/relay/src/behaviour.rs
  protocols/relay/src/priv_client.rs
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/src/server.rs
  protocols/request-response/src/lib.rs
  protocols/upnp/src/behaviour.rs
  swarm-derive/CHANGELOG.md
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/behaviour/either.rs
  swarm/src/behaviour/external_addresses.rs
  swarm/src/behaviour/listen_addresses.rs
  swarm/src/behaviour/toggle.rs
  swarm/src/connection.rs
  swarm/src/connection/pool.rs
  swarm/src/connection/pool/task.rs
  swarm/src/dummy.rs
  swarm/src/handler.rs
  swarm/src/lib.rs
  swarm/src/test.rs
  swarm/tests/connection_close.rs
  swarm/tests/listener.rs
  swarm/tests/swarm_derive.rs
Labels: send-it, internal-change

#4728 ci: use more workers for hole-punch test suite
  .github/workflows/interop-test.yml
Labels: send-it, trivial

#4624 fix(dcutr): exchange address candidates
  Cargo.lock
  examples/dcutr/src/main.rs
  hole-punching-tests/src/main.rs
  protocols/dcutr/CHANGELOG.md
  protocols/dcutr/Cargo.toml
  protocols/dcutr/src/behaviour.rs
  protocols/dcutr/src/handler/relayed.rs
  protocols/dcutr/src/lib.rs
  protocols/dcutr/tests/lib.rs
Labels: send-it

#4724 fix(request-response): don't keep duplicate addresses (v0.52 backport)
  Cargo.lock
  Cargo.toml
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/lib.rs
Labels: send-it, internal-change

#3914 refactor(request-response): don't use upgrade infrastructure
  Cargo.lock
  examples/file-sharing/src/network.rs
  protocols/autonat/CHANGELOG.md
  protocols/autonat/src/behaviour.rs
  protocols/autonat/src/behaviour/as_client.rs
  protocols/autonat/src/behaviour/as_server.rs
  protocols/autonat/tests/test_client.rs
  protocols/autonat/tests/test_server.rs
  protocols/rendezvous/src/client.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/handler.rs
  protocols/request-response/src/handler/protocol.rs
  protocols/request-response/src/lib.rs
  protocols/request-response/tests/error_reporting.rs
  protocols/request-response/tests/ping.rs
Labels: send-it

#4732 fix(libp2p): remove deprecated development_transport
  libp2p/CHANGELOG.md
  libp2p/src/lib.rs
  libp2p/src/tutorials/ping.rs
Labels: send-it

#4729 chore: remove deprecated `libp2p-deflate`
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  transports/deflate/CHANGELOG.md
  transports/deflate/Cargo.toml
  transports/deflate/src/lib.rs
  transports/deflate/tests/test.rs
Labels: send-it, trivial

#4548 refactor(noise): modify message framing
  Cargo.lock
  transports/noise/Cargo.toml
  transports/noise/src/io.rs
  transports/noise/src/io/framed.rs
  transports/noise/src/io/handshake.rs
  transports/noise/src/lib.rs
Labels: send-it

#4733 chore(kad): remove deprecated symbols
  protocols/kad/CHANGELOG.md
  protocols/kad/src/lib.rs
Labels: send-it, trivial

#4734 chore(plaintext): remove deprecated symbols
  transports/plaintext/CHANGELOG.md
  transports/plaintext/src/lib.rs
Labels: send-it, trivial

#4736 chore(core): remove deprecated symbols
  core/CHANGELOG.md
  core/src/transport.rs
Labels: send-it, trivial

#4698 chore: expose hashed_bytes of KBucketKey
  protocols/kad/CHANGELOG.md
  protocols/kad/src/kbucket/key.rs
Labels: send-it

#4739 chore(dns): remove deprecated symbols
  transports/dns/CHANGELOG.md
  transports/dns/src/lib.rs
Labels: send-it, trivial

#4740 chore(noise): remove unused attribute
  transports/noise/src/lib.rs
Labels: send-it, trivial

#4738 chore(quic): remove deprecated symbols
  transports/quic/CHANGELOG.md
  transports/quic/src/lib.rs
Labels: send-it, trivial

#4737 chore(swarm): remove deprecated symbols
  Cargo.lock
  libp2p/src/tutorials/ping.rs
  protocols/gossipsub/src/lib.rs
  protocols/request-response/src/cbor.rs
  swarm-derive/CHANGELOG.md
  swarm-derive/Cargo.toml
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/handler.rs
  swarm/src/lib.rs
  swarm/tests/ui/fail/out_event_deprecation.rs
  swarm/tests/ui/fail/out_event_deprecation.stderr
Labels: send-it, trivial

#4747 fix(hole-punch): don't explicitly close `RESERVE` stream
  protocols/relay/CHANGELOG.md
  protocols/relay/src/protocol/outbound_hop.rs
Labels: send-it, trivial

#4746 refactor(hole-punch): don't explicitly connect to the relay
  hole-punching-tests/src/main.rs
Labels: send-it, trivial

#4754 fix(floodsub): use `Bytes` for `FloodsubMessage::data`
  Cargo.lock
  protocols/floodsub/CHANGELOG.md
  protocols/floodsub/Cargo.toml
  protocols/floodsub/src/layer.rs
  protocols/floodsub/src/protocol.rs
Labels: send-it

#4758 deps: bump `cargo-semver-checks` to `v0.24.2`
  .github/workflows/ci.yml
Labels: send-it, trivial

#4744 refactor(relay): remove explicit stream tracking
  protocols/relay/src/behaviour.rs
  protocols/relay/src/behaviour/handler.rs
  protocols/relay/src/priv_client.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/relay/src/protocol/outbound_hop.rs
  protocols/relay/src/protocol/outbound_stop.rs
Labels: send-it

#4743 refactor(swarm-test): don't implicitly add external addresses
  misc/allow-block-list/src/lib.rs
  misc/connection-limits/src/lib.rs
  protocols/autonat/tests/test_client.rs
  protocols/dcutr/tests/lib.rs
  protocols/gossipsub/tests/smoke.rs
  protocols/identify/tests/smoke.rs
  protocols/kad/tests/client_mode.rs
  protocols/perf/tests/lib.rs
  protocols/ping/tests/ping.rs
  protocols/rendezvous/tests/rendezvous.rs
  protocols/request-response/tests/error_reporting.rs
  protocols/request-response/tests/ping.rs
  swarm-test/src/lib.rs
  swarm/tests/connection_close.rs
Labels: send-it, internal-change

#4748 ci: only lint for changes in `src/` & `Cargo.toml`
  scripts/ensure-version-bump-and-changelog.sh
Labels: send-it, trivial

#4735 chore(identify): remove deprecated symbols
  protocols/identify/CHANGELOG.md
  protocols/identify/src/behaviour.rs
  protocols/identify/src/handler.rs
  protocols/identify/tests/smoke.rs
Labels: send-it, trivial

#4721 fix(identify): only report observed address once per connection
  misc/metrics/CHANGELOG.md
  misc/metrics/src/swarm.rs
  protocols/dcutr/tests/lib.rs
  protocols/identify/CHANGELOG.md
  protocols/identify/src/behaviour.rs
  protocols/identify/tests/smoke.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/lib.rs
Labels: send-it

#4745 feat(relay): propagate errors to `Transport::{listen_on,dial}`
  Cargo.lock
  Cargo.toml
  hole-punching-tests/Cargo.toml
  hole-punching-tests/src/main.rs
  misc/futures-bounded/CHANGELOG.md
  misc/futures-bounded/Cargo.toml
  misc/futures-bounded/src/futures_map.rs
  misc/futures-bounded/src/futures_set.rs
  misc/futures-bounded/src/stream_map.rs
  misc/futures-bounded/src/stream_set.rs
  protocols/relay/CHANGELOG.md
  protocols/relay/Cargo.toml
  protocols/relay/src/lib.rs
  protocols/relay/src/priv_client.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/relay/src/priv_client/transport.rs
  protocols/relay/src/protocol/inbound_stop.rs
  protocols/relay/src/protocol/outbound_hop.rs
  protocols/relay/tests/lib.rs
Labels: send-it
