Repository libp2p/rust-libp2p, pull requests merged in 2023-08, with the labels that each got.

#4197 fix(examples/file-sharing): set Kademlia `Mode::Server`
  examples/file-sharing/src/network.rs
Labels: bug, send-it

#4257 docs: fix last OutboundQueryCompleted in kad doc
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
Labels: send-it

#4283 fix(relay): remove unconditional `async-std` dependency
  protocols/relay/CHANGELOG.md
  protocols/relay/Cargo.toml
Labels: send-it

#4278 fix(kad): reduce noise of "remote supports our protocol" log
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/handler.rs
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/connection.rs
Labels: send-it

#4281 feat: memory based connection limits
  Cargo.lock
  Cargo.toml
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  misc/memory-connection-limits/CHANGELOG.md
  misc/memory-connection-limits/Cargo.toml
  misc/memory-connection-limits/src/lib.rs
  misc/memory-connection-limits/tests/max_bytes.rs
  misc/memory-connection-limits/tests/max_percentage.rs
  misc/memory-connection-limits/tests/util.rs
Labels: send-it

#4289 fix(quic): allow listening on ipv4 and ipv6 separately
  Cargo.lock
  Cargo.toml
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/quic/src/transport.rs
Labels: send-it

#4312 chore: prepare libp2p v0.52.2
  libp2p/CHANGELOG.md
  misc/memory-connection-limits/CHANGELOG.md
  misc/metrics/CHANGELOG.md
  muxers/yamux/CHANGELOG.md
  protocols/gossipsub/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  protocols/relay/CHANGELOG.md
  protocols/request-response/CHANGELOG.md
  swarm/CHANGELOG.md
  transports/quic/CHANGELOG.md
Labels: send-it, trivial

#4304 fix(quic): add support for reusing an existing socket for local dialing
  Cargo.lock
  Cargo.toml
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/quic/src/transport.rs
  transports/quic/tests/smoke.rs
Labels: send-it

#4314 fix(swarm): import libp2p-yamux dev-dependency via path
  swarm/Cargo.toml
Labels: send-it, trivial

#4315 docs(roadmap): update to reflect ongoing wasm browser work
  ROADMAP.md
Labels: send-it

#4325 feat(quic): promote to stable release
  Cargo.lock
  Cargo.toml
  examples/chat-example/Cargo.toml
  examples/chat-example/src/main.rs
  examples/dcutr/Cargo.toml
  examples/dcutr/src/main.rs
  examples/relay-server/Cargo.toml
  examples/relay-server/src/main.rs
  interop-tests/Cargo.toml
  interop-tests/src/arch.rs
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
Labels: send-it

#4344 chore: use workspace `rust-version`
  libp2p/Cargo.toml
  misc/metrics/Cargo.toml
  protocols/kad/Cargo.toml
  swarm-test/Cargo.toml
Labels: send-it, trivial

#4340 docs: remove archived `ursa` project from README
  README.md
Labels: send-it

#4328 refactor(tcp): reducing branching in `Transport::create_socket`
  transports/quic/src/transport.rs
  transports/tcp/src/lib.rs
Labels: send-it

#4309 docs(readme): add taple to notable users
  README.md
Labels: send-it

#4352 refactor(.github): run cargo-deny on every pull request
  .github/workflows/cargo-deny-pr.yml
  .github/workflows/ci.yml
Labels: send-it

#4311 feat: add rust-libp2p-server to monorepo
  .github/workflows/ci.yml
  .github/workflows/docker-image.yml
  Cargo.lock
  Cargo.toml
  misc/server/CHANGELOG.md
  misc/server/Cargo.toml
  misc/server/Dockerfile
  misc/server/README.md
  misc/server/src/behaviour.rs
  misc/server/src/config.rs
  misc/server/src/http_service.rs
  misc/server/src/main.rs
Labels: send-it

#4378 deps(websocket): bump futures-rustls to 0.24.0
  Cargo.lock
  Cargo.toml
  transports/websocket/CHANGELOG.md
  transports/websocket/Cargo.toml
  transports/websocket/src/tls.rs
Labels: send-it

#4383 fix(interop/WASM): use selenium/standalone-chrome:115.0
  interop-tests/Dockerfile.chromium
Labels: send-it, trivial

#4379 refactor(identity): fix clippy beta lint
  identity/src/ed25519.rs
  identity/src/secp256k1.rs
Labels: send-it

#4381 deps(tls): switch from webpki to rustls-webpki
  Cargo.lock
  Cargo.toml
  transports/tls/CHANGELOG.md
  transports/tls/Cargo.toml
Labels: send-it

#4386 chore: fix lint warnings introduced by beta clippy
  muxers/mplex/src/io.rs
  protocols/gossipsub/src/backoff.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/gossip_promises.rs
  protocols/gossipsub/src/peer_score.rs
  protocols/gossipsub/src/time_cache.rs
  transports/quic/tests/smoke.rs
  wasm-tests/webtransport-tests/src/lib.rs
Labels: send-it

#4387 chore: prepare libp2p v0.52.3
  libp2p/CHANGELOG.md
  misc/server/CHANGELOG.md
  transports/noise/CHANGELOG.md
  transports/quic/CHANGELOG.md
  transports/tls/CHANGELOG.md
  transports/websocket/CHANGELOG.md
Labels: send-it

#4390 fix(misc/server): add repository URL to Cargo.toml
  misc/server/Cargo.toml
Labels: send-it, trivial

#4391 fix(misc/server): import libp2p as workspace dependency
  Cargo.toml
  misc/server/Cargo.toml
Labels: send-it

#4384 ci: do not tolerate rustc warnings in any job
  .cargo/config.toml
  .github/workflows/ci.yml
  identity/src/error.rs
  transports/webrtc/src/lib.rs
Labels: send-it

#4392 fix(misc/server): adhere to --metrics-path and listen on 0.0.0.0:8888
  Cargo.lock
  Cargo.toml
  misc/server/CHANGELOG.md
  misc/server/Cargo.toml
  misc/server/src/http_service.rs
  misc/server/src/main.rs
Labels: send-it

#4416 ci: don't test for semver violation for `libp2p-server` binary crate
  .github/workflows/ci.yml
Labels: send-it, trivial
