Repository libp2p/rust-libp2p, pull requests merged in 2023-07, with the labels that each got.

#4135 docs(swarm): fix stale docs around confirmed addresses
  swarm/src/behaviour.rs
Labels: send-it, trivial

#4137 fix(core/transport): update doc commment
  core/src/transport/boxed.rs
Labels: send-it, trivial

#4150 docs: mention open maintainer calls in README.md
  README.md
Labels: send-it, trivial

#4132 feat(kad): allow to explicitly set `Mode::{Client,Server}`
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour.rs
  protocols/kad/src/lib.rs
  protocols/kad/tests/client_mode.rs
Labels: send-it

#4133 feat(core): add logs for `OrTransport` when trying addresses
  core/src/transport/choice.rs
Labels: send-it

#4159 docs(swarm): document Swarm::external_addresses
  swarm/src/lib.rs
Labels: send-it, trivial

#4158 fix(swarm): external address candidate only after address translation
  Cargo.lock
  Cargo.toml
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/lib.rs
Labels: send-it

#4164 fix(core/choice): log on dial and fix listen log
  core/src/transport/choice.rs
Labels: send-it, trivial

#4163 chore: Update CHANGELOG.md
  swarm/CHANGELOG.md
Labels: send-it

#3861 ci: run interop tests on bigger hardware
  .github/workflows/interop-test.yml
Labels: send-it

#4166 chore: prepare libp2p-swarm v0.43.1 and libp2p-kad v0.44.2
  protocols/kad/CHANGELOG.md
  swarm/CHANGELOG.md
Labels: send-it

#4192 fix(interop): install `wasm-opt` in `Dockerfile.chromium`
  interop-tests/Dockerfile.chromium
Labels: send-it

#4195 fix(examples/kv-store): set kademlia mode to `Server`
  examples/distributed-key-value-store/src/main.rs
Labels: send-it

#4190 fix: clippy useless_conversion and useless_vec
  core/src/upgrade/apply.rs
  misc/allow-block-list/src/lib.rs
  misc/multistream-select/src/length_delimited.rs
  misc/multistream-select/tests/dialer_select.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/subscription_filter.rs
  transports/noise/tests/webtransport_certhashes.rs
Labels: send-it

#4211 chore: apply suggestions from clippy beta (1.72)
  muxers/mplex/src/lib.rs
  transports/dns/src/lib.rs
  transports/quic/src/transport.rs
  transports/uds/src/lib.rs
  transports/websocket/src/framed.rs
Labels: send-it, trivial

#4210 ci: automatically merge PRs of semver-compatible updates
  .github/mergify.yml
Labels: trivial

#4217 chore(gossipsub): include in `libp2p` meta crate when compiling for wasm
  Cargo.lock
  Cargo.toml
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  misc/metrics/CHANGELOG.md
  misc/metrics/Cargo.toml
  misc/metrics/src/identify.rs
  misc/metrics/src/lib.rs
Labels: send-it

#4162 feat(relay): add functions to `Limit` to access its data
  Cargo.lock
  Cargo.toml
  protocols/relay/CHANGELOG.md
  protocols/relay/Cargo.toml
  protocols/relay/src/protocol.rs
Labels: send-it

#4188 chore(libp2p): expose `json` feature from `request-response`
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
Labels: send-it

#4187 refactor(request-reponse): replace `serde_cbor` with `cbor4ii`
  Cargo.lock
  Cargo.toml
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/cbor.rs
Labels: send-it

#4224 fix(kad): prevent simultaneous dials to peer
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour.rs
Labels: send-it

#4193 feat(identity): implement from_protobuf_encoding for RSA keys
  Cargo.lock
  Cargo.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/error.rs
  identity/src/keypair.rs
  identity/src/rsa.rs
Labels: send-it

#4232 fix(swarm): display cause of denied listen error
  Cargo.lock
  Cargo.toml
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/lib.rs
Labels: send-it

#4250 fix(connection-limits): correct connection tracking
  Cargo.lock
  Cargo.toml
  misc/connection-limits/CHANGELOG.md
  misc/connection-limits/Cargo.toml
  misc/connection-limits/src/lib.rs
Labels: send-it

#4256 chore: prepare identity v0.2.2 and swarm v0.43.2
  identity/CHANGELOG.md
  swarm/CHANGELOG.md
Labels: send-it, trivial

#3454 refactor(quic): rewrite quic using quinn
  Cargo.lock
  Cargo.toml
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/quic/src/config.rs
  transports/quic/src/connection.rs
  transports/quic/src/connection/connecting.rs
  transports/quic/src/connection/stream.rs
  transports/quic/src/connection/substream.rs
  transports/quic/src/endpoint.rs
  transports/quic/src/hole_punching.rs
  transports/quic/src/lib.rs
  transports/quic/src/provider.rs
  transports/quic/src/provider/async_std.rs
  transports/quic/src/provider/tokio.rs
  transports/quic/src/transport.rs
  transports/quic/tests/smoke.rs
Labels: send-it

#4220 docs: add maintainer handbook
  docs/maintainer-handbook.md
Labels: send-it

#4265 docs(readme): rename iroh to beetle
  README.md
Labels: send-it, trivial

#4263 docs(readme): add Mina project as notable user
  README.md
Labels: send-it, trivial

#4264 docs(readme): add safe network to notable users
  README.md
Labels: send-it, trivial

#4228 fix(identity): use test fixture for ed25519
  identity/src/keypair.rs
Labels: send-it

#4267 chore: fix clippy
  Cargo.lock
  identity/src/keypair.rs
  transports/tls/src/lib.rs
Labels: send-it, trivial

#4262 chore(quic): prepare v0.9.0-alpha
  transports/quic/CHANGELOG.md
Labels: send-it, trivial

#4270 feat(kad): implement common traits on `RoutingUpdate`
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour.rs
Labels: send-it

#4227 chore(ci): bump `cargo semver-checks` to `0.22.1`
  .github/actions/cargo-semver-checks/action.yml
  .github/workflows/ci.yml
Labels: send-it

#4277 chore(roadmap): move QUIC quinn to done
  ROADMAP.md
Labels: send-it, trivial
