Repository libp2p/rust-libp2p, pull requests merged in 2023-12, with the labels that each got.

#4968 chore(webrtc-utils): bump version to allow for new release
  Cargo.lock
  Cargo.toml
  misc/webrtc-utils/CHANGELOG.md
  misc/webrtc-utils/Cargo.toml
Labels: send-it, trivial

#4932 fix(kad): iterator progress to be decided by any of new peers
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/query/peers/closest.rs
Labels: send-it

#4965 chore(quic): set `max_idle_timeout` to quinn default timeout
  Cargo.lock
  Cargo.toml
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/quic/src/config.rs
Labels: send-it

#4936 feat(core): impl Display on ListenerId
  Cargo.lock
  Cargo.toml
  core/CHANGELOG.md
  core/Cargo.toml
  core/src/transport.rs
Labels: send-it

#4937 feat(server): support websocket
  Cargo.lock
  Cargo.toml
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/builder/phase/relay.rs
  misc/server/CHANGELOG.md
  misc/server/Cargo.toml
  misc/server/src/main.rs
Labels: send-it

#4825 feat(swarm): implement `Copy` and `Clone` for `FromSwarm`
  Cargo.lock
  Cargo.toml
  protocols/autonat/src/behaviour.rs
  protocols/rendezvous/src/server.rs
  swarm-derive/CHANGELOG.md
  swarm-derive/Cargo.toml
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/behaviour.rs
  swarm/src/test.rs
Labels: send-it, internal-change

#4964 feat(connection-limit): add function to mutate `ConnectionLimits`
  Cargo.lock
  Cargo.toml
  misc/connection-limits/CHANGELOG.md
  misc/connection-limits/Cargo.toml
  misc/connection-limits/src/lib.rs
Labels: send-it

#4971 fix(kad): don't assume `QuerId`s are unique
  protocols/kad/src/handler.rs
Labels: send-it, internal-change

#4966 fix(webrtc example): clarify idle connection timeout
  examples/browser-webrtc/README.md
  examples/browser-webrtc/src/lib.rs
  examples/browser-webrtc/src/main.rs
Labels: send-it

#4984 docs(examples/readme): fix broken link
  examples/README.md
Labels: send-it

#4970 feat(yamux): auto-tune (dynamic) stream receive window
  Cargo.lock
  muxers/yamux/CHANGELOG.md
  muxers/yamux/Cargo.toml
  muxers/yamux/src/lib.rs
Labels: send-it

#4973 chore(webrtc-websys): remove unused dependencies
  Cargo.lock
  transports/webrtc-websys/Cargo.toml
Labels: send-it, trivial

#4993 chore(quic): fix link to PR in changelog
  transports/quic/CHANGELOG.md
Labels: send-it, trivial

#5020 docs: remove security@libp2p.io
  README.md
  SECURITY.md
Labels: send-it, trivial

#5021 chore: fix typos
  libp2p/src/transport_ext.rs
  protocols/relay/src/behaviour.rs
Labels: send-it

#5003 fix(derive): restore support for inline generic type constraints
  Cargo.lock
  Cargo.toml
  swarm-derive/CHANGELOG.md
  swarm-derive/Cargo.toml
  swarm-derive/src/lib.rs
  swarm/tests/swarm_derive.rs
Labels: send-it

#5008 chore: fix several typos in documentation
  transports/dns/src/lib.rs
  transports/noise/tests/smoke.rs
  transports/pnet/CHANGELOG.md
  transports/tls/src/certificate.rs
  transports/webrtc/src/tokio/udp_mux.rs
Labels: send-it

#5043 deps: bump Rust to 1.75 and fix clippy lints
  .github/workflows/ci.yml
  muxers/mplex/benches/split_send_size.rs
  muxers/mplex/src/io.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/kbucket.rs
  protocols/kad/src/kbucket/entry.rs
  protocols/relay/src/behaviour/rate_limiter.rs
  transports/dns/src/lib.rs
  transports/noise/src/lib.rs
  transports/webtransport-websys/src/error.rs
Labels: send-it
