Repository libp2p/rust-libp2p, pull requests merged in 2023-06, with the labels that each got.

#4016 refactor(dcutr): remove `direct::Handler`
  protocols/dcutr/src/behaviour_impl.rs
  protocols/dcutr/src/handler.rs
  protocols/dcutr/src/handler/direct.rs
Labels: send-it

#3974 docs(examples): add a README to each example
  examples/autonat/README.md
  examples/autonat/src/bin/autonat_client.rs
  examples/autonat/src/bin/autonat_server.rs
  examples/chat-example/README.md
  examples/chat-example/src/main.rs
  examples/dcutr/README.md
  examples/dcutr/src/main.rs
  examples/distributed-key-value-store/README.md
  examples/distributed-key-value-store/src/main.rs
  examples/file-sharing/README.md
  examples/file-sharing/src/main.rs
  examples/identify/README.md
  examples/identify/src/main.rs
  examples/ipfs-kad/Cargo.toml
  examples/ipfs-kad/README.md
  examples/ipfs-kad/src/main.rs
  examples/ipfs-private/README.md
  examples/ipfs-private/src/main.rs
  examples/metrics/README.md
  examples/metrics/src/main.rs
  examples/ping-example/README.md
  examples/ping-example/src/main.rs
  examples/relay-server/README.md
  examples/relay-server/src/main.rs
  examples/rendezvous/README.md
  examples/rendezvous/src/main.rs
Labels: send-it

#3960 feat(dcutr): keep connection alive while we are using it
  protocols/dcutr/CHANGELOG.md
  protocols/dcutr/src/behaviour_impl.rs
  protocols/dcutr/src/handler/relayed.rs
Labels: send-it

#4022 fix(relay): log when accepting reservation without external addresses
  protocols/relay/src/protocol/inbound_hop.rs
Labels: send-it, trivial

#4030 fix(swarm): make test not flaky
  swarm/src/behaviour/external_addresses.rs
Labels: send-it, trivial

#4031 ci: bump Rust version for clippy job to 1.70.0
  .github/workflows/ci.yml
Labels: send-it, trivial

#4032 chore(multistream-select): use futures_ringbuf
  Cargo.lock
  misc/multistream-select/Cargo.toml
  misc/multistream-select/src/length_delimited.rs
  misc/multistream-select/tests/dialer_select.rs
Labels: send-it, trivial

#4033 chore(multistream-select): replace mplex with yamux in tests
  Cargo.lock
  misc/multistream-select/Cargo.toml
  misc/multistream-select/tests/transport.rs
Labels: send-it, trivial

#4034 chore(rendezvous): remove unused dependency mplex
  Cargo.lock
  protocols/rendezvous/Cargo.toml
Labels: send-it, trivial

#3656 feat: remove `multiaddr` dependency from `libp2p-identity`
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/peer_id.rs
Labels: send-it

#4040 feat(core): remove deprecated `identity` module
  core/CHANGELOG.md
  core/Cargo.toml
  core/src/lib.rs
  protocols/gossipsub/src/error.rs
  protocols/gossipsub/src/lib.rs
  protocols/gossipsub/src/protocol.rs
  protocols/relay/src/priv_client/transport.rs
  swarm-test/src/lib.rs
  swarm/src/lib.rs
  transports/plaintext/src/error.rs
  transports/pnet/Cargo.toml
  transports/webrtc/src/tokio/transport.rs
Labels: send-it, trivial

#4036 feat(examples): use `cbor` codec in `file-sharing` example
  Cargo.lock
  examples/file-sharing/Cargo.toml
  examples/file-sharing/src/network.rs
  libp2p/Cargo.toml
Labels: send-it

#4042 chore(libp2p): remove non-existent features from `cfg`s
  libp2p/src/lib.rs
Labels: send-it, trivial

#4019 fix(multistream-select): don't wait for negotiation in poll_close
  misc/multistream-select/CHANGELOG.md
  misc/multistream-select/Cargo.toml
  misc/multistream-select/src/negotiated.rs
  misc/multistream-select/tests/dialer_select.rs
Labels: send-it

#4048 chore(identity): remove "unreleased" from v0.2.0 changelog entry
  identity/CHANGELOG.md
Labels: send-it, trivial

#4046 feat(request-response): use `cbor` codec in `ping` example
  protocols/request-response/tests/ping.rs
Labels: send-it

#4050 chore(kad): extend changelog entry on client/server mode
  protocols/kad/CHANGELOG.md
Labels: send-it, trivial

#4044 deps: run `cargo update`
  Cargo.lock
Labels: send-it, trivial

#4047 refactor(identity): fix import warnings in `keypair.rs`
  identity/src/keypair.rs
Labels: send-it

#3292 feat(swarm): allow `NetworkBehaviour`s to create and remove listeners
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/lib.rs
  swarm/src/listen_opts.rs
  swarm/tests/listener.rs
Labels: send-it

#4052 fix(examples): call `Swarm::add_external_address` in dcutr and relay
  examples/dcutr/src/main.rs
  examples/relay-server/src/main.rs
  protocols/identify/CHANGELOG.md
Labels: send-it, trivial

#4020 feat(swarm): add `ConnectionDenied::downcast_ref`
  swarm/CHANGELOG.md
  swarm/src/lib.rs
Labels: send-it

#4066 refactor(wasm-ext): replace `parity-send-wrapper` with `send-wrapper`
  Cargo.lock
  transports/wasm-ext/Cargo.toml
  transports/wasm-ext/src/lib.rs
Labels: send-it, trivial

#3964 feat(quic): implement hole punching
  Cargo.lock
  examples/dcutr/Cargo.toml
  examples/dcutr/src/main.rs
  examples/relay-server/Cargo.toml
  examples/relay-server/src/main.rs
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/quic/src/endpoint.rs
  transports/quic/src/hole_punching.rs
  transports/quic/src/lib.rs
  transports/quic/src/provider.rs
  transports/quic/src/provider/async_std.rs
  transports/quic/src/provider/tokio.rs
  transports/quic/src/transport.rs
Labels: send-it

#3991 feat(noise): add WebTransport certhashes extension
  Cargo.lock
  transports/noise/CHANGELOG.md
  transports/noise/Cargo.toml
  transports/noise/src/generated/payload.proto
  transports/noise/src/generated/payload/proto.rs
  transports/noise/src/io/framed.rs
  transports/noise/src/io/handshake.rs
  transports/noise/src/lib.rs
  transports/noise/tests/smoke.rs
  transports/noise/tests/webtransport_certhashes.rs
Labels: send-it

#4069 ci: attribute co-authorship of a PR based on its commits
  .github/mergify.yml
Labels: trivial

#4051 refactor(rendezvous): rewrite using `libp2p-request-response`
  Cargo.lock
  protocols/rendezvous/Cargo.toml
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/src/codec.rs
  protocols/rendezvous/src/handler.rs
  protocols/rendezvous/src/handler/inbound.rs
  protocols/rendezvous/src/handler/outbound.rs
  protocols/rendezvous/src/lib.rs
  protocols/rendezvous/src/server.rs
  protocols/rendezvous/src/substream_handler.rs
Labels: send-it

#4073 feat(rendezvous): directly return error from `register`
  examples/rendezvous/src/bin/rzv-identify.rs
  examples/rendezvous/src/bin/rzv-register.rs
  protocols/rendezvous/CHANGELOG.md
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/tests/rendezvous.rs
Labels: send-it

#4053 chore: prepare libp2p v0.52.0 release
  core/CHANGELOG.md
  libp2p/CHANGELOG.md
  misc/allow-block-list/CHANGELOG.md
  misc/connection-limits/CHANGELOG.md
  misc/metrics/CHANGELOG.md
  misc/multistream-select/CHANGELOG.md
  misc/quick-protobuf-codec/CHANGELOG.md
  misc/rw-stream-sink/CHANGELOG.md
  muxers/mplex/CHANGELOG.md
  muxers/yamux/CHANGELOG.md
  protocols/autonat/CHANGELOG.md
  protocols/dcutr/CHANGELOG.md
  protocols/floodsub/CHANGELOG.md
  protocols/gossipsub/CHANGELOG.md
  protocols/identify/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  protocols/mdns/CHANGELOG.md
  protocols/perf/CHANGELOG.md
  protocols/ping/CHANGELOG.md
  protocols/relay/CHANGELOG.md
  protocols/rendezvous/CHANGELOG.md
  protocols/request-response/CHANGELOG.md
  swarm-derive/CHANGELOG.md
  swarm-test/CHANGELOG.md
  swarm/CHANGELOG.md
  transports/deflate/CHANGELOG.md
  transports/dns/CHANGELOG.md
  transports/noise/CHANGELOG.md
  transports/plaintext/CHANGELOG.md
  transports/pnet/CHANGELOG.md
  transports/tcp/CHANGELOG.md
  transports/tls/CHANGELOG.md
  transports/uds/CHANGELOG.md
  transports/wasm-ext/CHANGELOG.md
  transports/websocket/CHANGELOG.md
Labels: send-it

#4090 fix(multistream-select): remove cyclic dependency to `libp2p-core`
  Cargo.lock
  misc/multistream-select/Cargo.toml
  misc/multistream-select/tests/transport.rs
Labels: send-it

#4091 chore: use `path` dependencies for all cyclic `dev-dependencies`
  core/Cargo.toml
  swarm/Cargo.toml
Labels: send-it

#4089 chore(quic,webrtc): prepare v0.8.0-alpha & v0.5.0-alpha
  transports/quic/CHANGELOG.md
  transports/webrtc/CHANGELOG.md
Labels: send-it

#4093 fix(cargo.toml): specify muxer harness by path only
  Cargo.toml
Labels: send-it

#4096 chore(roadmap): move QUIC hole punching to done
  ROADMAP.md
Labels: send-it, trivial

#4099 deps(webrtc): update webrtc to 0.8.0
  Cargo.lock
  transports/webrtc/Cargo.toml
Labels: send-it

#4100 fix(roadmap): correct table formatting
  ROADMAP.md
Labels: send-it, trivial

#4095 chore: add script for generating list of external contributors
  scripts/list-external-contributors.sh
Labels: send-it

#4015 feat(webtransport): add WebTransport for WASM environments
  .github/workflows/ci.yml
  .github/workflows/interop-test.yml
  Cargo.lock
  Cargo.toml
  interop-tests/Cargo.toml
  interop-tests/Dockerfile.chromium
  interop-tests/Dockerfile.native
  interop-tests/README.md
  interop-tests/chromium-ping-version.json
  interop-tests/native-ping-version.json
  interop-tests/pkg/readme.md
  interop-tests/src/arch.rs
  interop-tests/src/bin/config/mod.rs
  interop-tests/src/bin/native_ping.rs
  interop-tests/src/bin/ping.rs
  interop-tests/src/bin/wasm_ping.rs
  interop-tests/src/lib.rs
  libp2p/Cargo.toml
  libp2p/src/lib.rs
  transports/webtransport-websys/CHANGELOG.md
  transports/webtransport-websys/Cargo.toml
  transports/webtransport-websys/src/bindings.rs
  transports/webtransport-websys/src/connection.rs
  transports/webtransport-websys/src/endpoint.rs
  transports/webtransport-websys/src/error.rs
  transports/webtransport-websys/src/fused_js_promise.rs
  transports/webtransport-websys/src/lib.rs
  transports/webtransport-websys/src/stream.rs
  transports/webtransport-websys/src/transport.rs
  transports/webtransport-websys/src/utils.rs
  wasm-tests/README.md
  wasm-tests/run-all.sh
  wasm-tests/webtransport-tests/Cargo.toml
  wasm-tests/webtransport-tests/README.md
  wasm-tests/webtransport-tests/echo-server/.gitignore
  wasm-tests/webtransport-tests/echo-server/Dockerfile
  wasm-tests/webtransport-tests/echo-server/go.mod
  wasm-tests/webtransport-tests/echo-server/go.sum
  wasm-tests/webtransport-tests/echo-server/main.go
  wasm-tests/webtransport-tests/run.sh
  wasm-tests/webtransport-tests/src/lib.rs
Labels: send-it

#4106 chore: prepare libp2p v0.52.1
  Cargo.lock
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  transports/webtransport-websys/CHANGELOG.md
Labels: send-it

#4105 refactor(perf): expose single latency measurement
  protocols/perf/src/bin/perf.rs
Labels: send-it

#4107 feat(identity): expose `KeyType` for `PublicKey` and `Keypair`
  identity/CHANGELOG.md
  identity/src/keypair.rs
Labels: send-it

#4123 chore(webrtc): prepare v0.6.0-alpha
  Cargo.lock
  Cargo.toml
  transports/webrtc/CHANGELOG.md
  transports/webrtc/Cargo.toml
Labels: send-it, trivial

#4122 fix(test): only listen on `127.0.0.1` for ephemeral swarm
  misc/allow-block-list/src/lib.rs
  protocols/kad/tests/client_mode.rs
  protocols/mdns/tests/use-async-std.rs
  protocols/mdns/tests/use-tokio.rs
  swarm-test/src/lib.rs
Labels: send-it

#4109 fix(kad): re-expose Distance as KBucketDistance
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/lib.rs
Labels: send-it

#4125 fix(identity): bump version
  Cargo.lock
  Cargo.toml
  identity/Cargo.toml
Labels: send-it, trivial

#4128 chore(identity): prepare release for libp2p-identity 0.2.1
  identity/CHANGELOG.md
Labels: send-it, trivial

#4130 fix(ci): set `merge` attribute to false for non-merge commits
  .github/mergify.yml
Labels: trivial

#4131 fix: remove automated contribution message
  .github/mergify.yml
Labels: trivial

#4129 fix(kad): allow for different order of events in assertion
  protocols/kad/tests/client_mode.rs
Labels: send-it, trivial

#4134 docs: add `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: send-it
