Repository libp2p/rust-libp2p, pull requests merged in 2023-11, with the labels that each got.

#4749 refactor(dcutr): simplify public API
  Cargo.lock
  hole-punching-tests/src/main.rs
  libp2p/src/tutorials/hole_punching.rs
  misc/metrics/src/dcutr.rs
  protocols/dcutr/CHANGELOG.md
  protocols/dcutr/Cargo.toml
  protocols/dcutr/src/behaviour.rs
  protocols/dcutr/src/handler/relayed.rs
  protocols/dcutr/src/lib.rs
  protocols/dcutr/src/protocol/inbound.rs
  protocols/dcutr/src/protocol/outbound.rs
  protocols/dcutr/tests/lib.rs
Labels: send-it

#4718 feat(relay): don't close connections upon errors in relay server
  misc/metrics/src/relay.rs
  protocols/relay/CHANGELOG.md
  protocols/relay/src/behaviour.rs
  protocols/relay/src/behaviour/handler.rs
  protocols/relay/src/lib.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/relay/src/protocol/inbound_hop.rs
  protocols/relay/src/protocol/inbound_stop.rs
  protocols/relay/src/protocol/outbound_hop.rs
  protocols/relay/src/protocol/outbound_stop.rs
Labels: send-it, internal-change

#4783 refactor(plaintext): use `quick-protobuf-codec`
  Cargo.lock
  transports/plaintext/Cargo.toml
  transports/plaintext/src/error.rs
  transports/plaintext/src/handshake.rs
  transports/plaintext/src/lib.rs
Labels: send-it, trivial

#4784 chore: enforce that we don't have `dbg!` in our code
  Cargo.toml
  transports/noise/src/lib.rs
  transports/webrtc/tests/smoke.rs
Labels: send-it, trivial

#4785 ci: use dynamic PR base
  .github/workflows/ci.yml
  scripts/ensure-version-bump-and-changelog.sh
Labels: send-it, trivial

#4775 fix(webrtc): fix building for webrtc browser connectivity example
  .github/workflows/ci.yml
  examples/browser-webrtc/src/lib.rs
Labels: send-it

#4786 ci: fetch necessary refs
  .github/workflows/ci.yml
Labels: send-it, trivial

#4776 fix(relay): close stream once done sending
  protocols/relay/src/protocol/outbound_hop.rs
Labels: send-it, internal-change

#4787 refactor(autonat): use `quick-protobuf-codec`
  Cargo.lock
  protocols/autonat/Cargo.toml
  protocols/autonat/src/protocol.rs
Labels: send-it, trivial

#4788 feat(core): remove `upgrade::transfer` module
  core/CHANGELOG.md
  core/src/upgrade.rs
  core/src/upgrade/transfer.rs
Labels: send-it, trivial

#4581 feat(swarm): add `#[non_exhaustive]` to key enums
  .github/workflows/ci.yml
  Cargo.toml
  misc/allow-block-list/src/lib.rs
  misc/connection-limits/src/lib.rs
  misc/metrics/src/swarm.rs
  protocols/autonat/src/behaviour.rs
  protocols/dcutr/src/behaviour.rs
  protocols/dcutr/src/handler/relayed.rs
  protocols/floodsub/src/layer.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/handler.rs
  protocols/identify/src/behaviour.rs
  protocols/identify/src/handler.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/handler.rs
  protocols/perf/src/client/behaviour.rs
  protocols/perf/src/client/handler.rs
  protocols/perf/src/server/behaviour.rs
  protocols/perf/src/server/handler.rs
  protocols/ping/src/handler.rs
  protocols/ping/src/lib.rs
  protocols/relay/src/behaviour.rs
  protocols/relay/src/behaviour/handler.rs
  protocols/relay/src/priv_client.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/src/server.rs
  protocols/request-response/src/handler.rs
  protocols/request-response/src/lib.rs
  protocols/upnp/src/behaviour.rs
  swarm-derive/CHANGELOG.md
  swarm-derive/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/dummy.rs
  swarm/src/handler.rs
  swarm/src/lib.rs
  swarm/src/test.rs
  swarm/tests/swarm_derive.rs
Labels: send-it, internal-change

#4780 deps: migrate to `hickory-dns`
  Cargo.lock
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour/iface/dns.rs
  protocols/mdns/src/behaviour/iface/query.rs
  transports/dns/CHANGELOG.md
  transports/dns/Cargo.toml
  transports/dns/src/lib.rs
Labels: send-it

#4755 feat(swarm): don't have `ConnectionHandler`s close connections
  examples/file-sharing/src/network.rs
  misc/metrics/src/identify.rs
  misc/metrics/src/lib.rs
  misc/metrics/src/swarm.rs
  protocols/dcutr/src/handler/relayed.rs
  protocols/gossipsub/src/handler.rs
  protocols/identify/src/handler.rs
  protocols/kad/src/handler.rs
  protocols/perf/src/client/handler.rs
  protocols/perf/src/server/handler.rs
  protocols/ping/src/handler.rs
  protocols/relay/src/behaviour/handler.rs
  protocols/relay/src/priv_client/handler.rs
  protocols/request-response/src/handler.rs
  swarm-test/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/behaviour/toggle.rs
  swarm/src/connection.rs
  swarm/src/connection/error.rs
  swarm/src/connection/pool.rs
  swarm/src/connection/pool/task.rs
  swarm/src/dummy.rs
  swarm/src/handler.rs
  swarm/src/handler/either.rs
  swarm/src/handler/map_in.rs
  swarm/src/handler/map_out.rs
  swarm/src/handler/multi.rs
  swarm/src/handler/one_shot.rs
  swarm/src/handler/pending.rs
  swarm/src/handler/select.rs
  swarm/src/lib.rs
  swarm/tests/connection_close.rs
Labels: send-it, internal-change

#4795 chore: add changelog entry of backport
  swarm/CHANGELOG.md
Labels: send-it, trivial

#4794 fix(swarm): implement `ConnectionHandler::poll_close` for combinators
  swarm/src/behaviour/toggle.rs
  swarm/src/handler.rs
  swarm/src/handler/either.rs
  swarm/src/handler/map_in.rs
  swarm/src/handler/map_out.rs
  swarm/src/handler/multi.rs
  swarm/src/handler/select.rs
Labels: send-it, internal-change

#4796 chore: prepare v0.53.0
  core/CHANGELOG.md
  libp2p/CHANGELOG.md
  misc/allow-block-list/CHANGELOG.md
  misc/connection-limits/CHANGELOG.md
  misc/futures-bounded/CHANGELOG.md
  misc/memory-connection-limits/CHANGELOG.md
  misc/metrics/CHANGELOG.md
  muxers/mplex/CHANGELOG.md
  muxers/yamux/CHANGELOG.md
  protocols/autonat/CHANGELOG.md
  protocols/dcutr/CHANGELOG.md
  protocols/floodsub/CHANGELOG.md
  protocols/gossipsub/CHANGELOG.md
  protocols/identify/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  protocols/mdns/CHANGELOG.md
  protocols/perf/CHANGELOG.md
  protocols/ping/CHANGELOG.md
  protocols/relay/CHANGELOG.md
  protocols/rendezvous/CHANGELOG.md
  protocols/request-response/CHANGELOG.md
  protocols/upnp/CHANGELOG.md
  swarm-derive/CHANGELOG.md
  swarm-test/CHANGELOG.md
  swarm/CHANGELOG.md
  transports/dns/CHANGELOG.md
  transports/noise/CHANGELOG.md
  transports/plaintext/CHANGELOG.md
  transports/pnet/CHANGELOG.md
  transports/quic/CHANGELOG.md
  transports/tcp/CHANGELOG.md
  transports/tls/CHANGELOG.md
  transports/uds/CHANGELOG.md
  transports/websocket-websys/CHANGELOG.md
  transports/websocket/CHANGELOG.md
  transports/webtransport-websys/CHANGELOG.md
Labels: send-it, trivial, internal-change

#4812 fix(core): add impl `{In,Out}boundConnectionUpgrade` for `SelectUpgrade`
  Cargo.lock
  Cargo.toml
  core/CHANGELOG.md
  core/Cargo.toml
  core/src/upgrade/select.rs
Labels: send-it

#4831 fix: ensure `SwarmBuilder` multiplexer tests compile
  libp2p/src/builder.rs
Labels: send-it, internal-change

#4821 fix: Add `SwarmBuilder::with_quic_config` for `TcpPhase`
  Cargo.lock
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/builder.rs
  libp2p/src/builder/phase/tcp.rs
Labels: send-it

#4814 feat(kad): impl Display on QueryId
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/query.rs
Labels: send-it

#4816 fix(kad): potentially incorrect return value of `Addresses::remove`
  protocols/kad/CHANGELOG.md
  protocols/kad/src/addresses.rs
Labels: send-it

#4808 feat(libp2p): add `SwarmBuilder::with_dns_config`
  libp2p/CHANGELOG.md
  libp2p/src/builder.rs
  libp2p/src/builder/phase/dns.rs
  libp2p/src/builder/phase/other_transport.rs
  libp2p/src/builder/phase/quic.rs
  transports/dns/src/lib.rs
Labels: send-it, internal-change

#4727 feat(libp2p): track bandwidth per transport protocol stack
  Cargo.lock
  Cargo.toml
  examples/metrics/src/main.rs
  libp2p/CHANGELOG.md
  libp2p/src/bandwidth.rs
  libp2p/src/builder.rs
  libp2p/src/builder/phase.rs
  libp2p/src/builder/phase/bandwidth_logging.rs
  libp2p/src/builder/phase/bandwidth_metrics.rs
  libp2p/src/builder/phase/other_transport.rs
  libp2p/src/builder/phase/quic.rs
  libp2p/src/builder/phase/websocket.rs
  libp2p/src/transport_ext.rs
  misc/metrics/CHANGELOG.md
  misc/metrics/Cargo.toml
  misc/metrics/src/bandwidth.rs
  misc/metrics/src/lib.rs
  misc/server/CHANGELOG.md
  misc/server/Cargo.toml
  misc/server/src/main.rs
Labels: send-it

#4823 feat(quic): allow disabling of path MTU discovery
  Cargo.lock
  Cargo.toml
  transports/quic/CHANGELOG.md
  transports/quic/Cargo.toml
  transports/quic/src/config.rs
Labels: send-it

#4835 chore: prepare v0.53.1
  core/CHANGELOG.md
  libp2p/CHANGELOG.md
  misc/metrics/CHANGELOG.md
  misc/server/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  transports/quic/CHANGELOG.md
Labels: send-it

#4839 fix(dns): bump version
  Cargo.lock
  Cargo.toml
  transports/dns/CHANGELOG.md
  transports/dns/Cargo.toml
Labels: send-it

#4840 fix(chat-example): set `idle_connection_timeout`
  examples/chat/src/main.rs
Labels: send-it, trivial

#4779 deps(identity): bump `ring` to `v0.17.5`
  Cargo.lock
  Cargo.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/rsa.rs
Labels: send-it

#4833 feat(gossipsub): deprecate `Rpc` in preparation for making it private
  Cargo.lock
  Cargo.toml
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/lib.rs
Labels: send-it

#4855 chore: fix wrong or missing span names for `NetworkBehaviour::poll`
  protocols/autonat/src/behaviour.rs
  protocols/dcutr/src/behaviour.rs
  protocols/floodsub/src/layer.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/kad/src/behaviour.rs
  protocols/mdns/src/behaviour.rs
  protocols/perf/src/client/behaviour.rs
  protocols/perf/src/server/behaviour.rs
  protocols/relay/src/behaviour.rs
  protocols/relay/src/priv_client.rs
  protocols/rendezvous/src/client.rs
  protocols/rendezvous/src/server.rs
  protocols/request-response/src/lib.rs
  protocols/upnp/src/behaviour.rs
Labels: send-it, trivial

#4809 feat(relay): emit external address on reservation
  Cargo.lock
  Cargo.toml
  protocols/dcutr/tests/lib.rs
  protocols/relay/CHANGELOG.md
  protocols/relay/Cargo.toml
  protocols/relay/src/priv_client.rs
  protocols/relay/tests/lib.rs
Labels: send-it

#4596 fix: ensure `Multiaddr`s are `/p2p` terminated where possible
  Cargo.lock
  Cargo.toml
  protocols/identify/CHANGELOG.md
  protocols/identify/Cargo.toml
  protocols/identify/src/behaviour.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/addresses.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/protocol.rs
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour/iface/query.rs
  swarm/src/lib.rs
Labels: send-it, internal-change

#4854 chore(dcutr): fix typo in log statement
  protocols/dcutr/src/behaviour.rs
Labels: send-it

#4770 chore: activate `clippy::manual_let_else` lint
  Cargo.toml
  core/src/transport.rs
  core/src/transport/memory.rs
  core/tests/transport_upgrade.rs
  examples/browser-webrtc/src/main.rs
  examples/file-sharing/src/main.rs
  identity/src/ecdsa.rs
  misc/memory-connection-limits/src/lib.rs
  muxers/mplex/src/io.rs
  protocols/autonat/src/behaviour/as_client.rs
  protocols/autonat/src/behaviour/as_server.rs
  protocols/autonat/src/protocol.rs
  protocols/dcutr/src/behaviour.rs
  protocols/floodsub/src/layer.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/peer_score.rs
  protocols/gossipsub/src/protocol.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/query/peers/closest/disjoint.rs
  protocols/mdns/src/behaviour/iface/query.rs
  protocols/relay/src/priv_client/transport.rs
  protocols/relay/src/protocol/inbound_hop.rs
  protocols/rendezvous/src/codec.rs
  transports/noise/src/io/framed.rs
  transports/quic/src/transport.rs
  transports/quic/tests/smoke.rs
  transports/tcp/src/lib.rs
  transports/tls/src/upgrade.rs
  transports/webrtc-websys/src/connection.rs
  transports/webrtc/src/tokio/transport.rs
  transports/webrtc/tests/smoke.rs
Labels: send-it

#4778 feat(gossipsub): process send-queue before inbound stream
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/handler.rs
Labels: send-it

#4856 deps: bump all related `opentelemtry` dependencies together
  .github/dependabot.yml
Labels: send-it, trivial

#4857 deps: rename `trust-dns` dependabot group
  .github/dependabot.yml
Labels: send-it, trivial

#4865 fix(futures-bounded): register replaced `Stream`s/`Future`s as ready
  Cargo.lock
  Cargo.toml
  misc/futures-bounded/CHANGELOG.md
  misc/futures-bounded/Cargo.toml
  misc/futures-bounded/src/futures_map.rs
  misc/futures-bounded/src/futures_set.rs
  misc/futures-bounded/src/stream_map.rs
Labels: send-it, trivial

#4841 fix(relay): correctly track associated state of inflight streams
  Cargo.lock
  Cargo.toml
  misc/futures-bounded/CHANGELOG.md
  misc/futures-bounded/Cargo.toml
  misc/futures-bounded/src/futures_tuple_set.rs
  misc/futures-bounded/src/lib.rs
  protocols/relay/CHANGELOG.md
  protocols/relay/src/priv_client/handler.rs
Labels: send-it

#4862 fix(interop-tests): don't hardcode `x86_64` for native
  interop-tests/Dockerfile.native
Labels: send-it

#4879 chore(libp2p): add `#[allow(unreachable_pub)]`
  libp2p/src/builder/phase.rs
  libp2p/src/builder/select_muxer.rs
  libp2p/src/builder/select_security.rs
Labels: send-it, trivial

#4878 chore(relay): prepare `0.17.1` release
  protocols/relay/CHANGELOG.md
Labels: send-it, trivial

#4892 chore(futures-bounded): prepare release `0.2.3`
  misc/futures-bounded/CHANGELOG.md
Labels: send-it, trivial

#4893 docs: fix URLs in changelogs
  misc/futures-bounded/CHANGELOG.md
  protocols/relay/CHANGELOG.md
Labels: send-it

#4895 chore: bump version of `quick-protobuf-codec`
  Cargo.lock
  Cargo.toml
  misc/quick-protobuf-codec/CHANGELOG.md
  misc/quick-protobuf-codec/Cargo.toml
Labels: send-it, trivial

#4897 docs: fix typos
  README.md
  docs/coding-guidelines.md
  docs/release.md
Labels: send-it

#4899 deps: upgrade `cargo semver-checks` to `v0.25.0`
  .github/workflows/ci.yml
Labels: send-it, trivial

#4894 docs: document new CHANGELOG-management strategy
  docs/release.md
  protocols/gossipsub/CHANGELOG.md
  protocols/identify/CHANGELOG.md
  protocols/kad/CHANGELOG.md
  protocols/mdns/CHANGELOG.md
  scripts/add-changelog-header.sh
Labels: send-it

#4889 feat(websocket-websys): add support for different WASM environments
  Cargo.lock
  Cargo.toml
  transports/websocket-websys/CHANGELOG.md
  transports/websocket-websys/Cargo.toml
  transports/websocket-websys/src/lib.rs
  transports/websocket-websys/src/web_context.rs
Labels: send-it

#4887 fix: set `idle_connection_timeout` in examples
  examples/autonat/src/bin/autonat_client.rs
  examples/autonat/src/bin/autonat_server.rs
  examples/dcutr/src/main.rs
  examples/distributed-key-value-store/src/main.rs
  examples/file-sharing/src/network.rs
  examples/identify/src/main.rs
  examples/ipfs-private/src/main.rs
Labels: send-it

#4811 refactor(gossipsub): send more specific messages to `ConnectionHandler`
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/handler.rs
  protocols/gossipsub/src/protocol.rs
  protocols/gossipsub/src/types.rs
Labels: send-it

#4861 fix(mdns): don't suspend task forever upon reading non-mDNS packet
  protocols/mdns/CHANGELOG.md
  protocols/mdns/src/behaviour/iface.rs
Labels: send-it

#4901 refactor(kad): use `oneshot`s and `async-await` for outbound streams
  Cargo.lock
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour.rs
  protocols/kad/src/handler.rs
Labels: send-it

#4915 docs(interop-tests): minor fixes to README
  interop-tests/README.md
Labels: send-it

#4782 feat(quick-protobuf-codec): reduce allocations during encoding
  Cargo.lock
  Cargo.toml
  misc/quick-protobuf-codec/CHANGELOG.md
  misc/quick-protobuf-codec/Cargo.toml
  misc/quick-protobuf-codec/benches/codec.rs
  misc/quick-protobuf-codec/src/generated/mod.rs
  misc/quick-protobuf-codec/src/generated/test.proto
  misc/quick-protobuf-codec/src/generated/test.rs
  misc/quick-protobuf-codec/src/lib.rs
  misc/quick-protobuf-codec/tests/large_message.rs
Labels: send-it

#4940 ci: remove redundant comparison of features
  .github/workflows/ci.yml
Labels: send-it, trivial

#4938 ci: bump `axum`, `tower` and `tower-http` together
  .github/dependabot.yml
Labels: send-it, trivial

#4941 ci: always compare version in `CHANGELOG.md` and `Cargo.toml`
  .github/workflows/ci.yml
  scripts/ensure-version-bump-and-changelog.sh
Labels: send-it, trivial

#4866 chore(identity): don't inherit rust-version from workspace
  identity/Cargo.toml
Labels: send-it, trivial

#4900 refactor(relay): use oneshot's to track requested streams
  protocols/relay/src/priv_client/handler.rs
  protocols/relay/src/protocol/outbound_hop.rs
Labels: send-it

#4952 fix(browser-webrtc-example): use `tracing-wasm` logger
  Cargo.lock
  examples/browser-webrtc/Cargo.toml
  examples/browser-webrtc/src/lib.rs
Labels: send-it

#4949 fix(tutorial): import dependencies via meta crate
  libp2p/src/tutorials/ping.rs
Labels: send-it, internal-change

#4942 ci: unset `RUSTFLAGS` value in semver job
  .github/workflows/ci.yml
Labels: send-it

#4956 feat(request-response): derive `PartialOrd`,`Ord` for `{Out,In}RequestId`
  Cargo.lock
  Cargo.toml
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/lib.rs
Labels: send-it

#4958 refactor(connection-limits): make `check_limit` a free-function
  misc/connection-limits/src/lib.rs
Labels: send-it
