Repository libp2p/rust-libp2p, pull requests merged in 2024-03, with the labels that each got.

#5176 docs: extend idle connection timeout on ping tutorial
  libp2p/src/tutorials/ping.rs
Labels: send-it

#5210 chore: move `futures-bounded` out of mono-repo
  Cargo.lock
  Cargo.toml
  misc/futures-bounded/CHANGELOG.md
  misc/futures-bounded/Cargo.toml
  misc/futures-bounded/src/futures_map.rs
  misc/futures-bounded/src/futures_set.rs
  misc/futures-bounded/src/futures_tuple_set.rs
  misc/futures-bounded/src/lib.rs
  misc/futures-bounded/src/stream_map.rs
  misc/futures-bounded/src/stream_set.rs
Labels: send-it

#5197 chore(README/maintainers): remove mxinden
  README.md
Labels: send-it

#5181 deps: bump opentelemetry dependency
  Cargo.lock
  examples/metrics/Cargo.toml
  examples/metrics/src/main.rs
Labels: send-it, trivial

#5255 docs: fix typos in some comments
  core/src/transport.rs
  deny.toml
  examples/stream/README.md
  identity/src/secp256k1.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/config.rs
  protocols/kad/src/behaviour.rs
  protocols/kad/src/kbucket.rs
  swarm/src/connection.rs
  transports/websocket/src/framed.rs
Labels: send-it

#5229 fix(websocket-websys): change close code in drop implementation to 1000
  Cargo.lock
  Cargo.toml
  transports/websocket-websys/CHANGELOG.md
  transports/websocket-websys/Cargo.toml
  transports/websocket-websys/src/lib.rs
Labels: send-it

#5148 fix(kad): compute `jobs_query_capacity` accurately
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
Labels: send-it

#5270 feat(kad): FIND_NODE for own peer id returns closest peers
  Cargo.lock
  Cargo.toml
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour.rs
Labels: send-it

#3230 feat(dht)!: update republish interval and expiration time defaults
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
Labels: need/author-input, send-it

#5266 chore: raise MSRV to 1.75
  Cargo.toml
  hole-punching-tests/Dockerfile
  interop-tests/Dockerfile.chromium
  interop-tests/Dockerfile.native
  libp2p/CHANGELOG.md
Labels: send-it, trivial

#5273 fix(upnp): don't panic when gateway is dropped
  Cargo.lock
  Cargo.toml
  protocols/upnp/CHANGELOG.md
  protocols/upnp/Cargo.toml
  protocols/upnp/src/tokio.rs
Labels: send-it, trivial
