Repository libp2p/rust-libp2p, pull requests merged in 2024-12, with the labels that each got.

#5705 feat(kad): make Distance private field public
  Cargo.lock
  Cargo.toml
  protocols/kad/CHANGELOG.md
  protocols/kad/Cargo.toml
  protocols/kad/src/kbucket/key.rs
  protocols/kad/src/lib.rs
Labels: send-it-batch

#5721 chore: fix some typos in comment
  protocols/gossipsub/src/behaviour.rs
  swarm/src/dial_opts.rs
Labels: send-it

#5726 fix(libp2p): expose builder phase error
  libp2p/CHANGELOG.md
  libp2p/src/builder.rs
  libp2p/src/builder/phase.rs
  libp2p/src/lib.rs
Labels: send-it

#5719 feat(request-response): Add connection id to behaviour events
  Cargo.lock
  Cargo.toml
  protocols/autonat/CHANGELOG.md
  protocols/autonat/Cargo.toml
  protocols/autonat/src/v1/behaviour/as_client.rs
  protocols/autonat/src/v1/behaviour/as_server.rs
  protocols/rendezvous/CHANGELOG.md
  protocols/rendezvous/Cargo.toml
  protocols/rendezvous/src/server.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/lib.rs
  protocols/request-response/tests/error_reporting.rs
  protocols/request-response/tests/ping.rs
Labels: send-it

#5730 chore(ci): update Rust stable version
  .github/workflows/ci.yml
Labels: send-it

#5732 chore(roadmap): fix typo
  ROADMAP.md
Labels: send-it

#5727 fix: RUSTSEC-2024-0421 by upgrading idna
  Cargo.lock
  Cargo.toml
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour/iface/query.rs
  transports/dns/CHANGELOG.md
  transports/dns/Cargo.toml
  transports/dns/src/lib.rs
Labels: send-it

#5735 deps(metrics-example): update opentelemetry to 0.27
  Cargo.lock
  examples/metrics/Cargo.toml
  examples/metrics/src/main.rs
Labels: send-it, trivial

#5737 fix: update Cargo.lock
  Cargo.lock
Labels: send-it, trivial

#5734 chore(core): avoid unused props matching on connection.rs
  core/src/connection.rs
Labels: send-it

#4967 feat(swarm): set default for idle-connection-timeout to 10s
  examples/autonat/src/bin/autonat_client.rs
  examples/autonat/src/bin/autonat_server.rs
  examples/browser-webrtc/src/main.rs
  examples/chat/src/main.rs
  examples/dcutr/src/main.rs
  examples/distributed-key-value-store/src/main.rs
  examples/identify/src/main.rs
  examples/ipfs-kad/src/main.rs
  examples/ipfs-private/src/main.rs
  examples/metrics/src/main.rs
  examples/rendezvous/src/bin/rzv-discover.rs
  examples/rendezvous/src/bin/rzv-identify.rs
  examples/rendezvous/src/bin/rzv-register.rs
  examples/rendezvous/src/main.rs
  interop-tests/src/arch.rs
  libp2p/CHANGELOG.md
  libp2p/Cargo.toml
  libp2p/src/tutorials/ping.rs
  protocols/kad/src/behaviour/test.rs
  protocols/relay/tests/lib.rs
  swarm-test/CHANGELOG.md
  swarm-test/src/lib.rs
  swarm/CHANGELOG.md
  swarm/src/connection/pool.rs
  swarm/src/lib.rs
  transports/tls/tests/smoke.rs
Labels: send-it, internal-change

#5707 fix(identify): validate public key from remote peer
  Cargo.lock
  Cargo.toml
  protocols/identify/CHANGELOG.md
  protocols/identify/Cargo.toml
  protocols/identify/src/handler.rs
  protocols/identify/src/protocol.rs
  protocols/identify/tests/smoke.rs
Labels: send-it

#5739 deps(memory-connection-limits): update sysinfo to 0.33
  Cargo.lock
  misc/memory-connection-limits/Cargo.toml
  misc/memory-connection-limits/src/lib.rs
  misc/memory-connection-limits/tests/max_percentage.rs
Labels: send-it, trivial

#5575 feat(SwarmBuilder): add with_connection_timeout method
  libp2p/CHANGELOG.md
  libp2p/src/builder/phase/build.rs
  libp2p/src/builder/phase/swarm.rs
Labels: send-it

#5740 chore(core): use `matches!` in connection.rs
  core/src/connection.rs
Labels: send-it

#5742 chore: fix format with nightly
  libp2p/src/builder/phase.rs
  swarm/src/lib.rs
  transports/dns/src/lib.rs
Labels: send-it

#5744 chore(docs): fix typos in documentation
  docs/coding-guidelines.md
  protocols/gossipsub/CHANGELOG.md
Labels: send-it

#5715 fix(kad): improve memory allocation when iterating over kbuckets
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/kbucket.rs
Labels: send-it-batch

#5750 chore(spellchecker): fix typos in comment
  protocols/kad/src/behaviour/test.rs
Labels: send-it

#5749 chore: add SQD Network to notable users list
  README.md
Labels: send-it

#5753 feat(mdns): emit `ToSwarm::NewExternalAddrOfPeer` on discovery
  Cargo.lock
  Cargo.toml
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour.rs
Labels: send-it

#5756 fix: multiple typos of different importance
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  .github/workflows/ci.yml
Labels: send-it

#5747 chore(deps): remove unused deps
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  examples/autonat/Cargo.toml
  examples/autonatv2/Cargo.toml
  examples/chat/Cargo.toml
  examples/dcutr/Cargo.toml
  examples/distributed-key-value-store/Cargo.toml
  examples/file-sharing/Cargo.toml
  examples/identify/Cargo.toml
  examples/ipfs-kad/Cargo.toml
  examples/ipfs-private/Cargo.toml
  examples/ping/Cargo.toml
  examples/relay-server/Cargo.toml
  hole-punching-tests/Cargo.toml
  identity/Cargo.toml
  interop-tests/Cargo.toml
  libp2p/Cargo.toml
  misc/keygen/Cargo.toml
  misc/memory-connection-limits/Cargo.toml
  misc/multistream-select/Cargo.toml
  misc/server/Cargo.toml
  misc/server/src/config.rs
  misc/webrtc-utils/Cargo.toml
  protocols/autonat/Cargo.toml
  protocols/dcutr/Cargo.toml
  protocols/gossipsub/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/kad/Cargo.toml
  protocols/mdns/Cargo.toml
  protocols/perf/Cargo.toml
  protocols/ping/Cargo.toml
  protocols/rendezvous/Cargo.toml
  protocols/request-response/Cargo.toml
  swarm-derive/Cargo.toml
  swarm-test/Cargo.toml
  swarm/Cargo.toml
  transports/noise/Cargo.toml
  transports/plaintext/Cargo.toml
  transports/quic/Cargo.toml
  transports/tcp/Cargo.toml
  transports/tls/Cargo.toml
  transports/webrtc-websys/Cargo.toml
  transports/webrtc/Cargo.toml
  transports/websocket-websys/Cargo.toml
  wasm-tests/webtransport-tests/Cargo.toml
Labels: send-it

#5762 chore(mdns): revert version bump
  Cargo.lock
  Cargo.toml
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
Labels: send-it

#5757 deps(quic): update quinn to 0.11.6
  Cargo.lock
  transports/quic/Cargo.toml
Labels: send-it

#5725 chore: introduce `libp2p-test-utils`
  Cargo.lock
  Cargo.toml
  examples/autonatv2/Cargo.toml
  misc/multistream-select/Cargo.toml
  misc/multistream-select/src/dialer_select.rs
  misc/test-utils/CHANGELOG.md
  misc/test-utils/Cargo.toml
  misc/test-utils/src/lib.rs
  muxers/mplex/Cargo.toml
  muxers/mplex/benches/split_send_size.rs
  muxers/mplex/src/io.rs
  protocols/autonat/Cargo.toml
  protocols/autonat/tests/autonatv2.rs
  protocols/dcutr/Cargo.toml
  protocols/dcutr/tests/lib.rs
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/tests/smoke.rs
  protocols/identify/Cargo.toml
  protocols/identify/tests/smoke.rs
  protocols/kad/Cargo.toml
  protocols/kad/src/behaviour/test.rs
  protocols/kad/src/handler.rs
  protocols/kad/tests/client_mode.rs
  protocols/mdns/Cargo.toml
  protocols/mdns/tests/use-async-std.rs
  protocols/mdns/tests/use-tokio.rs
  protocols/perf/Cargo.toml
  protocols/perf/tests/lib.rs
  protocols/relay/Cargo.toml
  protocols/relay/tests/lib.rs
  protocols/rendezvous/Cargo.toml
  protocols/rendezvous/tests/rendezvous.rs
  protocols/request-response/Cargo.toml
  protocols/request-response/tests/error_reporting.rs
  protocols/request-response/tests/peer_address.rs
  protocols/request-response/tests/ping.rs
  protocols/stream/Cargo.toml
  protocols/stream/tests/lib.rs
  rustfmt.toml
  swarm/Cargo.toml
  swarm/src/connection.rs
  swarm/src/lib.rs
  transports/dns/Cargo.toml
  transports/dns/src/lib.rs
  transports/noise/Cargo.toml
  transports/noise/tests/smoke.rs
  transports/plaintext/Cargo.toml
  transports/plaintext/tests/smoke.rs
  transports/quic/Cargo.toml
  transports/quic/tests/smoke.rs
  transports/tcp/Cargo.toml
  transports/tcp/src/lib.rs
  transports/webrtc/Cargo.toml
  transports/webrtc/tests/smoke.rs
Labels: send-it

#5697 feat(gossipsub): implement gossipsub 1.2 beta
  Cargo.lock
  Cargo.toml
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/generated/gossipsub/pb.rs
  protocols/gossipsub/src/generated/rpc.proto
  protocols/gossipsub/src/gossip_promises.rs
  protocols/gossipsub/src/handler.rs
  protocols/gossipsub/src/metrics.rs
  protocols/gossipsub/src/protocol.rs
  protocols/gossipsub/src/rpc.rs
  protocols/gossipsub/src/types.rs
Labels: send-it

#5755 chore(deps): update Cargo.lock
  Cargo.lock
  transports/webrtc/Cargo.toml
  wasm-tests/webtransport-tests/src/lib.rs
Labels: send-it

#5770 feat(gossipsub): Allow setting a size threshold for IDONTWANT messages
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/config.rs
Labels: send-it
