Repository libp2p/rust-libp2p, pull requests merged in 2024-11, with the labels that each got.

#5613 fix(websocket): don't dial `/dnsaddr` addresses
  Cargo.lock
  Cargo.toml
  transports/websocket-websys/CHANGELOG.md
  transports/websocket-websys/Cargo.toml
  transports/websocket-websys/src/lib.rs
  transports/websocket/CHANGELOG.md
  transports/websocket/Cargo.toml
  transports/websocket/src/framed.rs
Labels: send-it

#5661 chore: fix some comments
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/peer_score/params.rs
Labels: send-it

#5663 chore: identify::Config fields private
  Cargo.lock
  Cargo.toml
  protocols/identify/CHANGELOG.md
  protocols/identify/Cargo.toml
  protocols/identify/src/behaviour.rs
Labels: send-it

#5665 chore(protocols): fix some typos in comment
  protocols/autonat/src/v2.rs
  protocols/identify/src/behaviour.rs
Labels: send-it

#5666 chore(ci): fix interop tests region, and run them again on each PR
  .github/workflows/interop-test.yml
  scripts/build-interop-image.sh
Labels: send-it, trivial

#5671 chore: replace async-std with tokio in autonat tests
  Cargo.lock
  protocols/autonat/Cargo.toml
  protocols/autonat/tests/test_client.rs
  protocols/autonat/tests/test_server.rs
Labels: send-it

#5668 chore(ci): add a mergify batch queue for external PRs
  .github/mergify.yml
  .github/workflows/interop-test.yml
  scripts/build-interop-image.sh
Labels: send-it

#5674 chore(gossispsub): deprecate futures-ticker
  Cargo.lock
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/peer_score.rs
Labels: send-it

#5685 chore: update FUNDING.json
  FUNDING.json
Labels: send-it

#5595 feat(gossipsub): introduce backpressure
  Cargo.lock
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/config.rs
  protocols/gossipsub/src/error.rs
  protocols/gossipsub/src/handler.rs
  protocols/gossipsub/src/lib.rs
  protocols/gossipsub/src/metrics.rs
  protocols/gossipsub/src/peer_score.rs
  protocols/gossipsub/src/peer_score/params.rs
  protocols/gossipsub/src/protocol.rs
  protocols/gossipsub/src/rpc.rs
  protocols/gossipsub/src/types.rs
Labels: send-it

#5689 chore(deps): upgrade `thiserror` to 2.0
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  identity/Cargo.toml
  libp2p/Cargo.toml
  misc/quick-protobuf-codec/Cargo.toml
  misc/webrtc-utils/Cargo.toml
  muxers/yamux/Cargo.toml
  protocols/autonat/Cargo.toml
  protocols/dcutr/Cargo.toml
  protocols/floodsub/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/kad/Cargo.toml
  protocols/perf/Cargo.toml
  protocols/relay/Cargo.toml
  protocols/rendezvous/Cargo.toml
  transports/noise/Cargo.toml
  transports/quic/Cargo.toml
  transports/tls/Cargo.toml
  transports/webrtc-websys/Cargo.toml
  transports/webrtc/Cargo.toml
  transports/websocket-websys/Cargo.toml
  transports/websocket/Cargo.toml
  transports/webtransport-websys/Cargo.toml
Labels: send-it

#5693 fix: typos in documentation files
  core/CHANGELOG.md
  identity/CHANGELOG.md
Labels: send-it

#5690 fix(gossipsub): fix mesh/fanout inconsistencies
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
Labels: send-it

#5700 fix(ci): Clippy Beta
  Cargo.lock
  Cargo.toml
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/backoff.rs
  protocols/gossipsub/src/behaviour.rs
  protocols/kad/CHANGELOG.md
  protocols/kad/src/jobs.rs
  protocols/kad/src/kbucket.rs
  protocols/kad/src/kbucket/bucket.rs
  protocols/kad/src/record.rs
  swarm/CHANGELOG.md
  swarm/src/connection/pool.rs
  transports/noise/CHANGELOG.md
  transports/noise/Cargo.toml
  transports/noise/src/io/handshake.rs
  transports/websocket-websys/CHANGELOG.md
  transports/websocket-websys/src/lib.rs
  transports/webtransport-websys/CHANGELOG.md
  transports/webtransport-websys/Cargo.toml
  transports/webtransport-websys/src/lib.rs
  wasm-tests/webtransport-tests/src/lib.rs
Labels: send-it-batch
