Repository libp2p/rust-libp2p, pull requests merged in 2024-07, with the labels that each got.

#5481 deps(ci): update cache-cargo-install-action
  .github/workflows/ci.yml
Labels: send-it, trivial

#5474 feat(kad): improve automatic bootstrap
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
  protocols/kad/src/bootstrap.rs
Labels: send-it

#5465 feat(swarm): Show task `spawn` paths in tokio-console
  Cargo.lock
  Cargo.toml
  protocols/mdns/CHANGELOG.md
  protocols/mdns/Cargo.toml
  protocols/mdns/src/behaviour.rs
  swarm/CHANGELOG.md
  swarm/src/connection/pool.rs
  swarm/src/executor.rs
Labels: send-it

#5026 fix(swarm): eliminating protocol cloning when nothing is happening
  Cargo.lock
  Cargo.toml
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/benches/connection_handler.rs
  swarm/src/connection.rs
  swarm/src/connection/supported_protocols.rs
  swarm/src/handler.rs
  swarm/src/lib.rs
Labels: send-it

#5483 chore(swarm): reword CHANGELOG.md
  Cargo.lock
  Cargo.toml
  swarm/CHANGELOG.md
  swarm/Cargo.toml
Labels: send-it, trivial

#5485 feat: Add `ConnectionError` to `FromSwarm::ConnectionClosed`
  Cargo.lock
  Cargo.toml
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/Cargo.toml
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/perf/CHANGELOG.md
  protocols/perf/Cargo.toml
  protocols/perf/src/client/behaviour.rs
  swarm/CHANGELOG.md
  swarm/src/behaviour.rs
  swarm/src/lib.rs
  swarm/src/test.rs
Labels: send-it

#5482 fix(webocket): Avoid panic when polling quicksink after errors
  Cargo.lock
  Cargo.toml
  transports/websocket/CHANGELOG.md
  transports/websocket/Cargo.toml
  transports/websocket/src/framed.rs
  transports/websocket/src/quicksink.rs
Labels: send-it

#5496 fix: rendezvous identify example
  examples/rendezvous/src/bin/rzv-identify.rs
Labels: send-it

#5498 fix(tls): fix rustls panic due to critical libp2p extension
  Cargo.lock
  Cargo.toml
  transports/tls/CHANGELOG.md
  transports/tls/Cargo.toml
  transports/tls/src/certificate.rs
  transports/tls/src/lib.rs
Labels: send-it

#5493 fix(relay): Add resource limits to `CircuitReq` to be set
  protocols/relay/CHANGELOG.md
  protocols/relay/src/protocol/inbound_hop.rs
Labels: send-it

#5511 fix: update Cargo.lock
  Cargo.lock
Labels: send-it, trivial

#5513 docs(README): Add Ceylon to the notable users section.
  README.md
Labels: rust, send-it

#5491 fix(relay): wake the relay Listener on close
  protocols/relay/CHANGELOG.md
  protocols/relay/src/priv_client/transport.rs
Labels: send-it

#5515 chore: address clippy beta lints
  hole-punching-tests/src/main.rs
  interop-tests/src/arch.rs
  protocols/ping/src/protocol.rs
Labels: send-it, trivial
