Repository libp2p/rust-libp2p, pull requests merged in 2024-01, with the labels that each got.

#5082 ci: add dependabot group for webrtc
  .github/dependabot.yml
Labels: send-it, trivial

#5027 feat: introduce `libp2p-stream`
  Cargo.lock
  Cargo.toml
  examples/stream/Cargo.toml
  examples/stream/README.md
  examples/stream/src/main.rs
  protocols/stream/CHANGELOG.md
  protocols/stream/Cargo.toml
  protocols/stream/README.md
  protocols/stream/src/behaviour.rs
  protocols/stream/src/control.rs
  protocols/stream/src/handler.rs
  protocols/stream/src/lib.rs
  protocols/stream/src/shared.rs
  protocols/stream/src/upgrade.rs
  protocols/stream/tests/lib.rs
Labels: send-it

#5083 chore: fix clippy lints
  protocols/gossipsub/src/behaviour/tests.rs
Labels: send-it, trivial

#5098 ci: update `cargo semver-checks` to `v0.27`
  .github/workflows/ci.yml
Labels: send-it, trivial

#5096 fix(upnp): ignore oneshot sender error when receiver is dropped
  Cargo.lock
  Cargo.toml
  protocols/upnp/CHANGELOG.md
  protocols/upnp/Cargo.toml
  protocols/upnp/src/tokio.rs
Labels: send-it

#5116 chore: update config.yml for new issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: send-it

#5118 chore(webrtc): release version 0.7.1-alpha
  Cargo.lock
  Cargo.toml
  transports/webrtc/CHANGELOG.md
  transports/webrtc/Cargo.toml
Labels: send-it, trivial

#4371 feat(swarm): allow behaviours to share addresses of peers
  Cargo.lock
  Cargo.toml
  protocols/autonat/Cargo.toml
  protocols/autonat/src/behaviour.rs
  protocols/dcutr/tests/lib.rs
  protocols/identify/CHANGELOG.md
  protocols/identify/Cargo.toml
  protocols/identify/src/behaviour.rs
  protocols/identify/tests/smoke.rs
  protocols/request-response/CHANGELOG.md
  protocols/request-response/Cargo.toml
  protocols/request-response/src/lib.rs
  protocols/request-response/tests/peer_address.rs
  swarm-derive/CHANGELOG.md
  swarm-derive/Cargo.toml
  swarm/CHANGELOG.md
  swarm/Cargo.toml
  swarm/src/behaviour.rs
  swarm/src/behaviour/peer_addresses.rs
  swarm/src/lib.rs
Labels: send-it, internal-change

#5056 docs(gossipsub): fix typos in error.rs
  protocols/gossipsub/src/error.rs
Labels: send-it
