Repository libp2p/rust-libp2p, pull requests merged in 2025-04, with the labels that each got.

#5972 fix(gossipsub): change message to message_id in trace
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
Labels: send-it

#5973 fix: update Cargo.lock
  Cargo.lock
Labels: send-it, trivial

#5868 feat(gossipsub): implement message sizes per topic.
  protocols/gossipsub/CHANGELOG.md
  protocols/gossipsub/src/behaviour.rs
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/config.rs
  protocols/gossipsub/src/error.rs
  protocols/gossipsub/src/protocol.rs
Labels: send-it

#5979 chore(metrics): update version and CHANGELOG.md
  Cargo.lock
  Cargo.toml
  misc/metrics/CHANGELOG.md
  misc/metrics/Cargo.toml
Labels: send-it, trivial

#5977 refactor(kad): replace BTreeMap::remove(Iter::next_back) with pop_last
  protocols/kad/src/behaviour.rs
Labels: send-it

#5926 feat(peer-store): Remove addresses from peer store on dial failure
  misc/peer-store/src/memory_store.rs
Labels: send-it

#5985 chore(ci): update Cargo.lock
  Cargo.lock
Labels: send-it, trivial

#5937 refactor(rz): simplify `discovered_peers` map
  protocols/rendezvous/src/client.rs
Labels: send-it

#5938 feat(request-response): add `Behaviour::send_request_with_addresses()`
  protocols/request-response/CHANGELOG.md
  protocols/request-response/src/lib.rs
  protocols/request-response/tests/ping.rs
Labels: send-it

#5989 docs(README): Add qaul messenger to the notable users section
  README.md
Labels: send-it

#5983 fix(gossipsub): use the protobuf max message size
  protocols/gossipsub/src/behaviour/tests.rs
  protocols/gossipsub/src/protocol.rs
Labels: send-it, trivial, internal-change

#5991 refactor(gossipsub): improve code legibility
  protocols/gossipsub/src/behaviour.rs
Labels: send-it

#5980 feat(kad): perform lazy cleanup for expired provider records
  protocols/kad/CHANGELOG.md
  protocols/kad/src/behaviour.rs
Labels: send-it

#5999 fix(stream): garbage-collect deregistered streams in `Shared::accept`
  Cargo.lock
  Cargo.toml
  examples/stream/Cargo.toml
  protocols/stream/CHANGELOG.md
  protocols/stream/Cargo.toml
  protocols/stream/src/shared.rs
Labels: send-it

#5934 docs: add getting started section to examples README
  examples/README.md
Labels: send-it

#5998 fix(upnp): panic during a shutdown process
  protocols/upnp/CHANGELOG.md
  protocols/upnp/src/behaviour.rs
Labels: send-it

#6010 fix(peer-store/memory-store): don't store remote address as listener
  misc/peer-store/src/memory_store.rs
Labels: send-it

#6000 fix(request-response): don't fail requests on `DialPeerConditionFalse`
  protocols/request-response/CHANGELOG.md
  protocols/request-response/src/lib.rs
  protocols/request-response/tests/ping.rs
Labels: send-it

#5892 feat(identity): switch from libsecp256k1 to k256
  Cargo.lock
  Cargo.toml
  identity/CHANGELOG.md
  identity/Cargo.toml
  identity/src/secp256k1.rs
Labels: send-it

#6011 refactor(peer-store): single behavior `Event`
  misc/peer-store/src/behaviour.rs
  misc/peer-store/src/lib.rs
  misc/peer-store/src/memory_store.rs
  misc/peer-store/src/store.rs
Labels: send-it
